import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import crypto from 'node:crypto';
import {contractDocument} from '../shared/contracts.js';
// Explicit disposable database only. No hosted credentials are loaded by this test.
test('contract lifecycle: snapshot, issue, lock, sign, replay, PDF, revoke and immutable storage', {skip:!process.env.V11_TEST_DATABASE_URL}, async()=>{
 const target=new URL(process.env.V11_TEST_DATABASE_URL);
 assert.ok(['localhost','127.0.0.1'].includes(target.hostname),'Use a disposable local database.');
 process.env.DATABASE_URL=process.env.V11_TEST_DATABASE_URL;
 process.env.NODE_ENV='test';delete process.env.APP_ENV;
 const {pool,query,transaction}=await import('../server/src/db/pool.js');
 const service=await import('../server/src/services/contract-service.js');
 const user=crypto.randomUUID(),client=crypto.randomUUID(),proposal=crypto.randomUUID();
 const req={user:{id:user},ip:'127.0.0.1',headers:{'user-agent':'LOLA contract test'}};
 try{await transaction(async()=>{
  const schema=`v11_${crypto.randomBytes(8).toString('hex')}`;
  await query(`CREATE SCHEMA ${schema}`);await query(`SET LOCAL search_path TO ${schema},public`);
  const directory=new URL('../server/migrations/',import.meta.url);
  for(const filename of (await fs.readdir(directory)).filter(name=>name.endsWith('.sql')).sort())await query(await fs.readFile(new URL(filename,directory),'utf8'));
  await query("INSERT INTO users(id,name,email,password_hash) VALUES($1,'QA Admin','qa-admin@example.invalid','test-only')",[user]);await query('INSERT INTO clients(id,name,email) VALUES($1,$2,$3)',[client,'Demo Client','client@example.com']);
  await query("INSERT INTO proposals(id,proposal_number,status,total,client_id,line_items_snapshot) VALUES($1,'DEMO-V11','ACCEPTED',1099,$2,$3)",[proposal,client,JSON.stringify([{description:'360 Signature',quantity:1,unit_price:1099}])]);
  const body={title:'Demo agreement',terms:'Approved demo service terms. A deposit is required to confirm the booking.'};
  const draft=await service.createContract(proposal,body,req);
  assert.equal((await service.createContract(proposal,body,req)).id,draft.id);
  const issued=await service.issueContract(draft.id,req);const token=issued.signing_url.split('/').at(-1);
  assert.equal(service.hashContractValue(contractDocument(issued.title,issued.terms,issued.snapshot)),issued.document_hash);
  assert.equal(await service.contractSigningUrl(draft.id),issued.signing_url);
  assert.ok(!('token_hash' in issued));assert.equal(Number((await service.publicContract(token)).snapshot.total),1099);
  await assert.rejects(service.updateContract(draft.id,{...body,terms:'Changed'},req));
  await assert.rejects(service.signContract(token,{name:'Demo Client',email:'wrong@example.com',consent:true,documentHash:issued.document_hash},req));
  const {sendContract}=await import('../server/src/services/contract-delivery-service.js');
  let sends=0;const send=async()=>{sends++;return {status:'SENT',provider:'test',providerMessageId:'test-message',deliveredExternally:true};};
  assert.equal((await sendContract(draft.id,req,{send})).status,'SENT_TO_PROVIDER');
  assert.equal((await sendContract(draft.id,req,{send})).replayed,true);assert.equal(sends,1);
  const signature={name:'Demo Client',email:'client@example.com',consent:true,documentHash:issued.document_hash};
  const signed=await service.signContract(token,signature,req);assert.equal(signed.status,'SIGNED');
  assert.equal((await service.signContract(token,signature,req)).signed_at.getTime(),signed.signed_at.getTime());
  assert.equal((await query("SELECT count(*)::int AS n FROM audit_logs WHERE action='contract_signed'")).rows[0].n,1);
  assert.equal((await query('SELECT status FROM proposals WHERE id=$1',[proposal])).rows[0].status,'ACCEPTED');
  const {workspaceAccess,publicWorkspace,revokeWorkspace}=await import('../server/src/services/client-workspace-service.js');
  const access=await workspaceAccess(proposal,req),workspaceToken=access.url.split('/').at(-1);
  assert.equal((await publicWorkspace(workspaceToken)).agreements[0].status,'SIGNED');
  assert.equal((await workspaceAccess(proposal,req)).url,access.url);
  await revokeWorkspace(proposal,req);await assert.rejects(publicWorkspace(workspaceToken));
  const blocked=()=>{throw Object.assign(new Error('Not allowlisted'),{code:'STAGING_RECIPIENT_BLOCKED'});};
  await assert.rejects(sendContract(draft.id,req,{send,policy:blocked}));assert.equal(sends,1);
  assert.equal((await sendContract(draft.id,req,{send:async()=>{throw Object.assign(new Error('Timeout'),{code:'MICROSOFT_REQUEST_TIMEOUT'});}})).status,'UNKNOWN');
  await assert.rejects(sendContract(draft.id,req,{send}));assert.equal(sends,1);
  const pdf=await service.contractPdf(signed);assert.equal(pdf.subarray(0,4).toString(),'%PDF');
  await query('SAVEPOINT immutability');await assert.rejects(query("UPDATE contracts SET terms='tampered' WHERE id=$1",[draft.id]),/immutable/);await query('ROLLBACK TO SAVEPOINT immutability');
  await assert.rejects(service.revokeContract(draft.id,req));
  const revised=await service.createContract(proposal,body,req);assert.equal(revised.revision,2);
  const replacement=await service.issueContract(revised.id,req);const replacementToken=replacement.signing_url.split('/').at(-1);
  await service.revokeContract(revised.id,req);await assert.rejects(service.publicContract(replacementToken));
  const expired=await service.createContract(proposal,body,req);const expIssued=await service.issueContract(expired.id,req);await query("UPDATE contracts SET expires_at=now()-interval '1 second' WHERE id=$1",[expired.id]);await assert.rejects(service.publicContract(expIssued.signing_url.split('/').at(-1)));
  await query(`DROP SCHEMA ${schema} CASCADE`);
 });}finally{await pool.end();}
});
