import test from 'node:test';
import assert from 'node:assert/strict';
import {marketingPayload,dispatchMarketing,stableEventId,marketingConfiguration} from '../server/src/services/marketing-adapters.js';
const config={GA4_ENABLED:'true',GA4_MEASUREMENT_ID:'G-LOCAL',GA4_API_SECRET:'secret-not-logged',META_EVENTS_ENABLED:'true',META_PIXEL_ID:'123',META_ACCESS_TOKEN:'secret-not-logged',META_GRAPH_VERSION:'v24.0',TIKTOK_EVENTS_ENABLED:'true',TIKTOK_PIXEL_ID:'123',TIKTOK_ACCESS_TOKEN:'secret-not-logged'};
const fixture=provider=>({provider,event_name:'payment_completed',created_at:'2026-09-24T12:00:00Z',idempotency_key:provider+':payment:1',payload:{value:100,currency:'USD',email:'private@example.invalid',attribution:{ga_client_id:'123.456',ga_session_id:'123',fbclid:'click123',fbclid_timestamp:1790251200000,ttclid:'click456',email:'private@example.invalid'}}});
for(const provider of ['GA4','META','TIKTOK']){
 test(`${provider} is disabled by default without any transport call`,async()=>{assert.equal(marketingConfiguration(provider,{}).enabled,false);assert.equal((await dispatchMarketing(fixture(provider),{config:{},transport:()=>assert.fail('No external request')})).result,'DISABLED');});
 test(`${provider} payload is deterministic, minimal and uses stable provider identity`,async()=>{const job=fixture(provider),body=marketingPayload(job,config);assert.ok(!JSON.stringify(body).includes('private'));assert.ok(JSON.stringify(body).includes(stableEventId(job)));let calls=0;const result=await dispatchMarketing(job,{config,transport:async(url,options)=>{calls++;assert.equal(options.method,'POST');assert.deepEqual(JSON.parse(options.body),body);return new Response(JSON.stringify(provider==='META'?{events_received:1}:{code:0}),{status:200});}});assert.equal(calls,1);assert.equal(result.mode,'PROVIDER');assert.ok(!JSON.stringify(result).includes('secret'));});
 test(`${provider} rejects invalid payloads and redacts uncertain outcomes`,async()=>{assert.throws(()=>marketingPayload({...fixture(provider),event_name:'unapproved'},config));await assert.rejects(()=>dispatchMarketing(fixture(provider),{config,transport:async()=>{throw new Error('secret-not-logged')}}),e=>e.code==='PROVIDER_OUTCOME_UNKNOWN'&&!e.message.includes('secret'));});
}
test('GA4 does not retry ambiguous ingestion; Meta rate limits remain retryable',async()=>{for(const provider of ['GA4','META'])await assert.rejects(()=>dispatchMarketing(fixture(provider),{config,transport:async()=>new Response('{}',{status:429})}),e=>e.retryable===(provider==='META'));});
