import {useState} from 'react';
import {Link} from 'react-router-dom';
import {UsersRound,Send,Mail,MousePointerClick,Image,FileText,MessageSquare,ArrowRight,Upload,CalendarDays} from 'lucide-react';
const formats=[['HTML','HTML Email','Create a custom, branded email.',Image],['CORPORATE','Template Email','Use the year-end campaign design.',FileText],['TEXT','Text Email','Send a simple text-only message.',MessageSquare]];
export default function CampaignDashboard({campaigns,contacts,onCreate,onImport,canCreate,canTemplates,children}){
 const [format,setFormat]=useState('HTML'),[audience,setAudience]=useState(''),[later,setLater]=useState(false);
 const unique=[...new Map(contacts.filter(c=>c.email).map(c=>[c.email.trim().toLowerCase(),c])).values()];
 const active=unique.filter(c=>c.marketing_email_opt_in===true&&c.communication_preferences?.marketing_email!==false&&!c.communication_preferences?.unsubscribed);
 const companies=[...new Set(contacts.map(c=>c.company).filter(Boolean))].sort();
 const sum=key=>campaigns.reduce((n,c)=>n+Number(c[key]||0),0),sent=sum('sent'),tracked=sum('tracked');
 const upcoming=campaigns.filter(c=>c.status==='SCHEDULED'&&c.scheduled_at).sort((a,b)=>new Date(a.scheduled_at)-new Date(b.scheduled_at));
 const bars=campaigns.filter(c=>Number(c.sent)>0).slice(0,8).reverse(),max=Math.max(1,...bars.map(c=>Number(c.sent)));
 return <div className="campaign-dashboard"><div className="campaign-stat-grid">{[[UsersRound,active.length.toLocaleString(),'Consented CRM contacts','Before campaign suppression checks'],[Send,sent.toLocaleString(),'Emails sent','Across the campaigns shown below'],[Mail,tracked?(sum('opened')/tracked*100).toFixed(1)+'%':'—','Estimated open rate','Unique opens / tracked recipients'],[MousePointerClick,tracked?(sum('clicked')/tracked*100).toFixed(1)+'%':'—','Click rate','Unique clicks / tracked recipients']].map(([Icon,value,label,note])=><article className="campaign-stat" key={label}><span className="campaign-stat-icon"><Icon size={26}/></span><div><strong>{value}</strong><span>{label}</span><small>{note}</small></div></article>)}</div>
 <div className="campaign-dashboard-columns"><div className="campaign-dashboard-main"><section className="campaign-panel campaign-quick-create"><h2>Quick Create</h2><p className="campaign-section-note">Choose your campaign type, audience and send time.</p><div className="campaign-format-choices">{formats.map(([key,name,note,Icon])=><button key={key} onClick={()=>setFormat(key)} aria-pressed={key===format} className={key===format?'selected':''}><span className="campaign-format-icon"><Icon size={28}/></span><strong>{name}</strong><span>{note}</span><span className="campaign-radio" aria-hidden="true"/></button>)}</div><div className="campaign-quick-fields"><label className="campaign-field">Audience<select value={audience} onChange={e=>setAudience(e.target.value)}><option value="">Select an audience…</option><option value="CONSENTED">Consented CRM contacts</option><option value="LEADS">Leads</option><option value="CLIENTS">Clients</option>{companies.map(name=><option key={name} value={'COMPANY:'+name}>{name}</option>)}</select></label><label className="campaign-field">Send time<select value={later?'LATER':'NOW'} onChange={e=>setLater(e.target.value==='LATER')}><option value="NOW">Send now</option><option value="LATER">Schedule for later</option></select></label><button disabled={!canCreate} className="primary-action" onClick={()=>onCreate(format,audience,later)}>Start Campaign <ArrowRight size={18}/></button></div></section>
 <div className="campaign-dashboard-duo"><section className="campaign-panel"><div className="campaign-section-heading"><div><h2>Contacts &amp; Audiences</h2><p className="campaign-section-note">Grow your audience and keep it organized.</p></div>{canCreate&&<button onClick={onImport}><Upload size={15}/> Upload CSV / Excel</button>}</div><div className="campaign-audience-summary"><div><strong>{unique.length.toLocaleString()}</strong><span>CRM contacts</span><small>Imported recipients stay with their campaign.</small></div><div className="campaign-audience-links">{[['Leads',contacts.filter(c=>c.kind==='lead').length,'LEADS'],['Clients',contacts.filter(c=>c.kind==='client').length,'CLIENTS'],['Consented contacts',active.length,'CONSENTED']].map(([label,count,key])=><button disabled={!canCreate} key={key} onClick={()=>onCreate(format,key,false)}><span><i/> {label}</span><strong>{count.toLocaleString()}</strong><ArrowRight size={14}/></button>)}</div></div></section><section className="campaign-panel"><div className="campaign-section-heading"><div><h2>Templates</h2><p className="campaign-section-note">Start with a design and make it your own.</p></div>{canTemplates&&<Link to="/sales/communications?section=Templates">View all →</Link>}</div><div className="campaign-template-grid">{[['CORPORATE','Corporate Year-End','/campaigns/year-end-2026/hero.jpg'],['HTML','Custom HTML','/brand/proposals/approved/wedding-event.jpg'],['TEXT','Personal Message','/brand/proposals/approved/glam.jpg']].map(([key,name,image])=><button disabled={!canCreate} key={key} onClick={()=>onCreate(key,'',false)}><img src={image} alt=""/><strong>{name}</strong><small>{key==='HTML'?'Paste or upload your design':key==='TEXT'?'Write your message':'Approved starter design'}</small></button>)}</div></section></div>
 <section className="campaign-panel campaign-recent"><div className="campaign-section-heading"><div><h2>Recent Campaigns</h2><p className="campaign-section-note">Your campaigns and their latest performance.</p></div><span>{campaigns.length} campaigns</span></div>{children}</section></div>
 <aside className="campaign-dashboard-side"><section className="campaign-brand-card"><img src="/brand/proposals/approved/glam.jpg" alt="The LOLA photo booth experience"/><div><h2>Turn moments<br/>into lasting<br/>relationships.</h2><i/><p>Beautiful events.<br/>Brighter inboxes.</p></div></section><section className="campaign-panel"><h2>Campaign Performance</h2><p className="campaign-section-note">Sent recipients by recent campaign</p>{bars.length?<div className="campaign-bar-chart" role="img" aria-label={bars.map(c=>c.name+': '+c.sent+' sent').join('; ')}>{bars.map(c=><Link key={c.id} to={'/communications/campaigns/'+c.id} title={c.name+': '+c.sent+' sent'}><span style={{height:Math.max(3,Number(c.sent)/max*120)}}/><small>{c.sent}</small></Link>)}</div>:<div className="campaign-small-empty">Performance appears after your first send.</div>}<p className="campaign-tracking-note">Opens are estimates. Delivery confirmation is not available from this email provider.</p></section><section className="campaign-panel"><h2>Upcoming Sends</h2>{upcoming.length?upcoming.slice(0,4).map(c=><Link className="campaign-upcoming" key={c.id} to={'/communications/campaigns/'+c.id}><CalendarDays size={21}/><span><strong>{c.name}</strong><small>{new Date(c.scheduled_at).toLocaleString('en-US',{timeZone:c.timezone})} · {c.timezone}</small></span></Link>):<p className="campaign-small-empty">No scheduled campaigns.</p>}<blockquote>“Connection creates opportunity.”<small>THE LOLA BOOTH</small></blockquote></section></aside></div></div>;
}
