import {useEffect,useState} from 'react';
import {api} from '../../api/client.js';
import {loadCatalog} from '../../../shared/catalog-loading.js';
import {campaignContent,campaignOfferPrice,campaignPackageOffer} from '../../../shared/campaign-content.js';
const steps=['Campaign','Recipients','Offers','Review & send'];
const money=n=>'$'+Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
function Input({label,value,onChange,type='text',...rest}){return <label className="campaign-field">{label}{type==='textarea'?<textarea aria-label={label} rows={8} value={value||''} onChange={e=>onChange(e.target.value)} {...rest}/>:<input aria-label={label} type={type} value={value??''} onChange={e=>onChange(type==='number'?Number(e.target.value):e.target.value)} {...rest}/>}</label>;}
export default function CampaignBuilder({draft,setDraft,contacts,audience,busy,initialStep=0,onSave,onClose,onDelivery,onTest,canSend,canSchedule,schedule,setSchedule,testEmail,setTestEmail,run}){
 const [htmlUpload,setHtmlUpload]=useState(null);
 const [senders,setSenders]=useState([]),[senderError,setSenderError]=useState(''),[step,setStep]=useState(Math.min(initialStep,3)),[search,setSearch]=useState(''),[imported,setImported]=useState(null),[catalog,setCatalog]=useState(null),[catalogError,setCatalogError]=useState(''),[attempt,setAttempt]=useState(0),[preview,setPreview]=useState(null),[mobile,setMobile]=useState(false),[sample,setSample]=useState(''),[newContact,setNewContact]=useState({email:'',first_name:'',last_name:'',company:'',phone:'',marketing_email_opt_in:false});
 useEffect(()=>{let active=true;api.get('/campaigns/senders').then(rows=>active&&setSenders(rows)).catch(e=>active&&setSenderError(e.message));return()=>{active=false;};},[]);
 const c=campaignContent(draft.content_json),a=draft.audience_json;
 const change=(key,value)=>setDraft(d=>({...d,[key]:value}));
 const content=(key,value)=>setDraft(d=>({...d,content_json:{...campaignContent(d.content_json),[key]:value}}));
 const audienceChange=(key,value)=>setDraft(d=>({...d,audience_json:{...d.audience_json,[key]:value}}));
 useEffect(()=>{let active=true;setCatalogError('');Promise.all(['experiences','packages','addons'].map(r=>loadCatalog(api.get,r))).then(([experiences,packages,addons])=>{if(active)setCatalog({experiences:experiences.filter(x=>x.active!==false&&x.is_active!==false),packages:packages.filter(x=>x.active!==false&&x.is_active!==false),addons:addons.filter(x=>x.active!==false&&x.is_active!==false)});}).catch(e=>active&&setCatalogError(e.message));return()=>{active=false;};},[attempt]);
 const htmlImageKeys=[...new Set([...c.html_body.matchAll(/\{\{(?:assets?|images)\.([\w.]+)\}\}/g)].map(m=>m[1]))];
 const contentFingerprint=JSON.stringify(draft.content_json);
 // Reloading a saved draft must not dismiss an identical generated preview.
 useEffect(()=>setPreview(null),[contentFingerprint,draft.subject,draft.preview_text]);
 const updateOffer=(key,patch)=>content('offers',c.offers.map(o=>o.key===key?{...o,...patch}:o));
 function toggle(item,kind){const key=kind+'_'+item.id;content('offers',c.offers.some(o=>o.key===key)?c.offers.filter(o=>o.key!==key):[...c.offers,{key,kind,catalog_id:item.id,package_id:null,name:item.website_name||item.name,description:item.description||'',image_url:item.image_url||'',hours:kind==='EXPERIENCE'?4:0,original_price:Number(item.base_price??item.price??0),discount_type:'NONE',discount_value:0}]);}
 async function uploadContacts(file){if(!file)return;if(file.size>2*1024*1024)throw new Error('Choose a contact file up to 2 MB.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));setImported(await api.post('/campaigns/import-contacts',{filename:file.name,data:btoa(binary)}));}
 async function uploadHtml(file){if(!file)return;if(!/\.html?$/i.test(file.name)||file.size>250000)throw new Error('Choose an HTML file up to 250 KB.');const html=(await file.text()).replace(/^\uFEFF/,'');if(!html.trim())throw new Error('The HTML file is empty. Choose a file containing your email design.');content('html_body',html);setHtmlUpload({name:file.name,characters:html.length});}
 async function previewCampaign(){const saved=await onSave();setPreview(await api.post('/campaigns/'+saved.id+'/preview',{sample:contacts.find(x=>x.id===sample)||{first_name:'Jordan',company:'Northstar Group'}}));}
 function next(){if(step===0&&(!draft.name.trim()||!draft.subject.trim()||(c.format==='TEXT'&&!c.text_body.trim())||(c.format==='HTML'&&!c.html_body.trim())))throw new Error('Add the campaign name, subject and message before continuing.');setStep(v=>Math.min(v+1,3));}
 return <><nav className="campaign-tabs" aria-label="Campaign steps">{steps.map((name,i)=><button key={name} onClick={()=>setStep(i)} className={step===i?'active':''} aria-current={step===i?'step':undefined}>{i+1}. {name}</button>)}</nav><section className="campaign-panel campaign-builder">
 {step===0&&<><h2>What would you like to send?</h2><div className="campaign-format-choices">{[['TEXT','Text campaign','Write your message in a simple form.'],['HTML','HTML campaign','Paste or upload your own email design.'],['CORPORATE','Year-end template','Use the approved corporate campaign.']].map(([key,name,note])=><button key={key} className={c.format===key?'selected':''} aria-pressed={c.format===key} onClick={()=>content('format',key)}><strong>{name}</strong><span>{note}</span></button>)}</div><Input label="Campaign name" value={draft.name} onChange={v=>change('name',v)} placeholder="December corporate offer" required/><Input label="Email subject" value={draft.subject} onChange={v=>change('subject',v)} required/><Input label="Preview text (optional)" value={draft.preview_text} onChange={v=>change('preview_text',v)}/>
 {c.format==='TEXT'?<><Input label="Headline" value={c.headline} onChange={v=>content('headline',v)}/><Input label="Your message" type="textarea" value={c.text_body} onChange={v=>content('text_body',v)} placeholder="Hi {{contact.first_name}},\nCelebrate with your team…"/></>:c.format==='HTML'?<><label className="campaign-field">Upload HTML<input type="file" accept=".html,.htm,text/html" onChange={e=>{const file=e.target.files[0];if(file)run(()=>uploadHtml(file));}}/></label>{htmlUpload&&<p role="status">Loaded {htmlUpload.name} · {htmlUpload.characters.toLocaleString()} characters. Your HTML is in the editor below.</p>}<Input label="Or paste your HTML" className="campaign-html-editor" type="textarea" value={c.html_body} onChange={v=>{content('html_body',v);setHtmlUpload(null);}} placeholder="<!doctype html>…"/><p>Use {'{{offers}}'} where the selected offer cards should appear and {'{{interest_url}}'} for your button link. If omitted, offers are added beneath your design. Unsubscribe is included automatically.</p>{htmlImageKeys.length>0&&<section><h3>Campaign images</h3><p>Add the image URL for each placeholder in your HTML. These links must be publicly accessible over HTTPS.</p>{htmlImageKeys.map(key=><Input key={key} label={'Image URL — '+key} value={c.images[key]||''} onChange={v=>content('images',{...c.images,[key]:v})} placeholder="https://…"/>)}</section>}<p>Images must have public HTTPS URLs. Active scripts and forms are removed from email content.</p></>:<><Input label="Headline" value={c.headline} onChange={v=>content('headline',v)}/><Input label="Intro" type="textarea" value={c.intro} onChange={v=>content('intro',v)}/><p>The approved Glam, 360 and Duo offers remain in this template. Choose Text or HTML to build an offer from the catalog.</p><div className="campaign-grid">{['glam','360','duo'].map(k=><div key={k}><Input label={k+' price ($)'} type="number" min="0" value={c[k+'_price']} onChange={v=>content(k+'_price',v)}/><Input label={k+' extra hour ($)'} type="number" min="0" value={c[k+'_extra']} onChange={v=>content(k+'_extra',v)}/></div>)}</div></>}
 <label className="campaign-field">Send from<select disabled={busy || !!senderError} value={draft.sender_email||''} onChange={e=>{const selected=senders.find(s=>s.email===e.target.value);setDraft(d=>({...d,sender_email:e.target.value,sender_name:selected?.name||d.sender_name,reply_to:e.target.value||d.reply_to}));}}><option value="">{senders.find(s=>!s.email)?.label||'Default mailbox'}</option>{senders.filter(s=>s.email).map(s=><option key={s.email} value={s.email}>{s.name} &lt;{s.email}&gt;</option>)}</select></label>{senderError&&<p role="alert">Sender options could not load: {senderError}</p>}<details><summary>Sender and personalization</summary><div className="campaign-grid"><Input label="Sender name" value={draft.sender_name} onChange={v=>change('sender_name',v)}/><Input label="Reply-to email" type="email" value={draft.reply_to} onChange={v=>change('reply_to',v)}/></div><p>Available fields: {'{{contact.first_name}}'}, {'{{contact.last_name}}'}, {'{{contact.full_name}}'}, {'{{contact.email}}'} and {'{{company.name}}'}.</p></details></>}
 {step===1&&<><h2>Who should receive it?</h2><p>{audience?.count??'…'} eligible recipients. Addresses are checked for marketing consent, duplicates and unsubscribe preferences.</p><section className="campaign-import"><h3>Upload a contact list</h3><a href="/campaigns/contact-import-template.xlsx" download>Download Excel template</a><label className="campaign-field">Upload completed Excel or CSV<input type="file" accept=".xlsx,.csv" onChange={e=>{const file=e.target.files[0];e.target.value='';run(()=>uploadContacts(file));}}/></label><p>Up to 1,000 contacts / 2 MB. The Contacts sheet uses Email, First Name, Last Name, Company, Phone and Marketing Consent.</p>{imported&&<><p>{imported.total} valid contacts · {imported.duplicates} duplicates removed · {imported.withoutConsent} without consent</p>{imported.errors.length>0&&<div role="alert"><strong>Correct these rows before importing:</strong><ul>{imported.errors.map((e,i)=><li key={i}>Row {e.row}: {e.message}</li>)}</ul></div>}<button disabled={busy||imported.errors.length>0||!imported.total} onClick={()=>{const existing=new Set((a.manual||[]).map(r=>r.email.trim().toLowerCase()));audienceChange('manual',[...(a.manual||[]),...imported.recipients.filter(r=>!existing.has(r.email))]);setImported(null);}}>Add reviewed contacts</button><button onClick={()=>setImported(null)}>Discard upload</button></>}</section>
 <h3>Select CRM contacts</h3><Input label="Search contacts or companies" value={search} onChange={setSearch}/><div className="campaign-contact-picker">{contacts.filter(r=>(r.email+' '+r.first_name+' '+r.company).toLowerCase().includes(search.toLowerCase())).map(r=><label className="campaign-selection" key={r.kind+'_'+r.id}><input type="checkbox" checked={a.ids.includes(r.id)} onChange={e=>audienceChange('ids',e.target.checked?[...a.ids,r.id]:a.ids.filter(id=>id!==r.id))}/><span>{r.first_name} {r.last_name}<small>{r.email} · {r.company||'No company'}{!r.marketing_email_opt_in?' · No marketing consent':''}</small></span></label>)}</div><details><summary>Choose companies, tags or lead source</summary><div className="campaign-grid"><Input label="Companies (one per line)" type="textarea" value={(a.companies||[]).join('\n')} onChange={v=>audienceChange('companies',v.split('\n').filter(Boolean))}/><Input label="Tags (one per line)" type="textarea" value={(a.tags||[]).join('\n')} onChange={v=>audienceChange('tags',v.split('\n').filter(Boolean))}/><Input label="Lead source" value={a.source} onChange={v=>audienceChange('source',v)}/></div></details>
 <details><summary>Add one recipient</summary><div className="campaign-grid">{[['email','Email'],['first_name','First name'],['last_name','Last name'],['company','Company'],['phone','Phone']].map(([key,label])=><Input key={key} label={label} type={key==='email'?'email':'text'} value={newContact[key]} onChange={v=>setNewContact(r=>({...r,[key]:v}))}/>)}</div><label><input type="checkbox" checked={newContact.marketing_email_opt_in} onChange={e=>setNewContact(r=>({...r,marketing_email_opt_in:e.target.checked}))}/> I have this recipient’s marketing consent</label><button onClick={()=>run(async()=>{if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(newContact.email))throw new Error('Enter a valid email address.');audienceChange('manual',[...(a.manual||[]),newContact]);setNewContact({email:'',first_name:'',last_name:'',company:'',phone:'',marketing_email_opt_in:false});})}>Add contact</button></details>
 {!!a.manual?.length&&<details open><summary>{a.manual.length} imported / manual recipients</summary>{a.manual.map((r,i)=><div key={i} className="campaign-selection"><span>{r.first_name} {r.last_name} · {r.email}<small>{r.company} · {r.marketing_email_opt_in?'Consent confirmed':'No consent — excluded'}</small></span><button onClick={()=>audienceChange('manual',a.manual.filter((_,j)=>i!==j))}>Remove</button></div>)}</details>}{!!audience?.excluded?.length&&<details><summary>{audience.excluded.length} excluded recipients</summary>{audience.excluded.map((r,i)=><p key={i}>{r.email}: {r.reason}</p>)}</details>}</>}
 {step===2&&<><h2>Build your offer</h2><p>Select experiences and add-ons, then set the prices and discounts your recipients will see.</p>{c.format==='CORPORATE'?<p>The year-end template uses its three approved packages. Switch to Text or HTML in step 1 to choose catalog experiences and discounts.</p>:<>{catalogError?<p role="alert">{catalogError} <button onClick={()=>setAttempt(v=>v+1)}>Retry catalog</button></p>:!catalog?<p>Loading catalog…</p>:<><h3>Experiences</h3><div className="campaign-offer-picker">{catalog.experiences.map(x=><button key={x.id} aria-pressed={c.offers.some(o=>o.catalog_id===x.id)} className={c.offers.some(o=>o.catalog_id===x.id)?'selected':''} onClick={()=>toggle(x,'EXPERIENCE')}><strong>{x.website_name||x.name}</strong><small>{money(x.base_price||0)}</small></button>)}</div><h3>Add-ons</h3><div className="campaign-offer-picker">{catalog.addons.map(x=><button key={x.id} aria-pressed={c.offers.some(o=>o.catalog_id===x.id)} className={c.offers.some(o=>o.catalog_id===x.id)?'selected':''} onClick={()=>toggle(x,'ADDON')}>{x.name}<small>{money(x.price||0)}</small></button>)}</div>{!catalog.experiences.length&&<p>No experiences are available in the catalog.</p>}</>}
 {c.offers.map(o=>{const price=campaignOfferPrice(o);return <section className="campaign-offer-edit" key={o.key}><div className="campaign-toolbar"><h3>{o.name}</h3><button onClick={()=>content('offers',c.offers.filter(x=>x.key!==o.key))}>Remove</button></div>{o.kind==='EXPERIENCE'&&<label className="campaign-field">Package (optional)<select value={o.package_id||''} onChange={e=>{const p=catalog?.packages.find(p=>p.id===e.target.value);updateOffer(o.key,p?campaignPackageOffer(o,p):{package_id:null});}}><option value="">Custom campaign offer</option>{catalog?.packages.filter(p=>!p.experience_id||p.experience_id===o.catalog_id).map(p=><option key={p.id} value={p.id}>{p.name} · {money(p.starting_price??p.price??0)}</option>)}</select></label>}<div className="campaign-grid"><Input label="Offer name" value={o.name} onChange={v=>updateOffer(o.key,{name:v})}/>{o.kind==='EXPERIENCE'&&<Input label="Hours of service" type="number" min="0" max="48" value={o.hours} onChange={v=>updateOffer(o.key,{hours:v})}/>}<Input label="Original price ($)" type="number" min="0" step="0.01" value={o.original_price} onChange={v=>updateOffer(o.key,{original_price:v})}/><label className="campaign-field">Discount<select value={o.discount_type} onChange={e=>updateOffer(o.key,{discount_type:e.target.value,discount_value:0})}><option value="NONE">No discount</option><option value="PERCENT">Percentage (%)</option><option value="AMOUNT">Dollar amount ($)</option></select></label>{o.discount_type!=='NONE'&&<Input label={o.discount_type==='PERCENT'?'Discount (%)':'Discount ($)'} type="number" min="0" max={o.discount_type==='PERCENT'?100:o.original_price} step="0.01" value={o.discount_value} onChange={v=>updateOffer(o.key,{discount_value:v})}/>}</div><Input label="Offer details / included features" type="textarea" value={o.description} onChange={v=>updateOffer(o.key,{description:v})}/><Input label="Image URL (optional, HTTPS)" value={o.image_url} onChange={v=>updateOffer(o.key,{image_url:v})}/><p className="campaign-discount-preview">{price.saving>0&&<s>{money(price.original)}</s>} <strong>{money(price.discounted)}</strong>{price.saving>0&&<span> Save {money(price.saving)}</span>}</p></section>;})}{!c.offers.length&&<p>Offers are optional. Your campaign can simply introduce your business or invite a conversation.</p>}</>}
 <Input label="Call-to-action button" value={c.cta} onChange={v=>content('cta',v)}/><Input label="Footer contact details" value={c.footer} onChange={v=>content('footer',v)}/><Input label="Business mailing address" value={c.mailing_address} onChange={v=>content('mailing_address',v)}/></>}
 {step===3&&<><h2>Preview and send</h2><p><strong>{draft.name}</strong> · {audience?.count??'…'} eligible recipients · {c.format==='HTML'?'HTML':c.format==='TEXT'?'Text':'Year-end template'}</p><label className="campaign-field">Preview recipient<select value={sample} onChange={e=>setSample(e.target.value)}><option value="">Jordan · Northstar Group</option>{contacts.map(r=><option key={r.kind+'_'+r.id} value={r.id}>{r.first_name} · {r.company||r.email}</option>)}</select></label><div className="campaign-toolbar"><button disabled={busy} onClick={()=>run(previewCampaign)}>Generate preview</button><button onClick={()=>setMobile(v=>!v)}>{mobile?'Desktop':'Mobile (375px)'}</button></div>{preview&&<><p><strong>Subject:</strong> {preview.subject}</p><iframe title="Campaign email preview" sandbox="" srcDoc={preview.html} style={{width:mobile?375:680,maxWidth:'100%',height:650,border:'1px solid #ddd'}}/></>}
 <Input label="Test email address" type="email" value={testEmail} onChange={setTestEmail}/>{canSend&&<button disabled={busy} onClick={()=>onTest(contacts.find(x=>x.id===sample)||{first_name:'Jordan',company:'Northstar Group'})}>Send test</button>}<div className="campaign-grid"><Input label="Schedule date and time (optional)" type="datetime-local" value={schedule} onChange={setSchedule}/><Input label="Timezone" value={draft.timezone} onChange={v=>change('timezone',v)}/></div><div className="campaign-toolbar">{canSend&&<button disabled={busy} className="primary-action" onClick={()=>onDelivery('send')}>Send now</button>}{canSchedule&&<button disabled={busy||!schedule} onClick={()=>onDelivery('schedule')}>Schedule</button>}</div></>}
 <div className="campaign-step-footer"><button disabled={busy} onClick={()=>step?setStep(v=>v-1):onClose()}>{step?'Back':'Cancel'}</button><div className="campaign-toolbar"><button disabled={busy} onClick={()=>run(onSave)}>Save draft</button>{step<3&&<button disabled={busy} className="primary-action" onClick={()=>run(async()=>next())}>Continue →</button>}</div></div></section></>;
}
