import { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, Download, Columns3, ChevronDown } from 'lucide-react';
import DataTable from '../DataTable.jsx';
import { labelize } from '../../utils/display.js';
import '../../styles/record-workspace.css';
export function csvCell(value){const text=String(value??'');return '"'+(/^[=+@\-\t\r]/.test(text)?"'"+text:text).replaceAll('"','""')+'"';}
export default function RecordTable({title='Records',rows=[],columns,...props}){
 const [page,setPage]=useState(1),[hidden,setHidden]=useState([]),[sort,setSort]=useState(''),[direction,setDirection]=useState(1),[selected,setSelected]=useState([]);
 useEffect(()=>{setPage(1);setSelected(old=>old.filter(id=>rows.some(row=>row.id===id)));},[rows]);
 const visible=columns.filter(column=>!hidden.includes(column));
 const sorted=useMemo(()=>sort?[...rows].sort((a,b)=>{const left=a[sort],right=b[sort];return direction*(typeof left==='number'&&typeof right==='number'?left-right:String(left??'').localeCompare(String(right??''),undefined,{numeric:true}));}):rows,[rows,sort,direction]);
 const pages=Math.max(1,Math.ceil(rows.length/10)),active=Math.min(page,pages),displayed=sorted.slice((active-1)*10,active*10);
 function download(){const exportRows=selected.length?sorted.filter(row=>selected.includes(row.id)):sorted;const csv=[visible.map(column=>csvCell(props.columnLabels?.[column]||labelize(column))).join(','),...exportRows.map(row=>visible.map(column=>csvCell(row[column])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=title.toLowerCase().replaceAll(' ','-')+'.csv';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function sortBy(column){setDirection(sort===column?-direction:1);setSort(column);setPage(1);}
 const selection={ids:selected,toggle:(id,checked)=>setSelected(old=>checked?[...new Set([...old,id])]:old.filter(value=>value!==id)),toggleAll:(items,checked)=>setSelected(old=>checked?[...new Set([...old,...items.map(row=>row.id)])]:old.filter(id=>!items.some(row=>row.id===id)))};
 const pageNumbers=Array.from({length:Math.min(5,pages)},(_,index)=>Math.max(1,Math.min(active-2,pages-4))+index);
 return <section className="record-panel record-table-panel"><header><h2>{title} <span>({rows.length})</span></h2><div className="button-row"><button onClick={download} disabled={!rows.length}><Download size={15}/>{selected.length?`Export ${selected.length} selected`:'Export'}</button><details className="record-columns"><summary><Columns3 size={15}/>Columns<ChevronDown size={12}/></summary><div>{columns.map(column=><label key={column}><input type="checkbox" checked={!hidden.includes(column)} disabled={visible.length===1&&!hidden.includes(column)} onChange={()=>setHidden(old=>old.includes(column)?old.filter(value=>value!==column):[...old,column])}/>{props.columnLabels?.[column]||labelize(column)}</label>)}</div></details></div></header><DataTable {...props} compactActions selection={selection} onSort={sortBy} sortKey={sort} sortDirection={direction} rows={displayed} columns={visible}/><footer><span>{rows.length?`Showing ${(active-1)*10+1}–${Math.min(active*10,rows.length)} of ${rows.length} loaded records`:'No records'}{selected.length?` · ${selected.length} selected`:''}</span><nav aria-label={`${title} pages`}><button aria-label="Previous records" disabled={active<=1} onClick={()=>setPage(current=>current-1)}><ChevronLeft size={16}/></button>{pageNumbers.map(number=><button key={number} className={active===number?'record-current-page':''} aria-label={`Page ${number}`} aria-current={active===number?'page':undefined} onClick={()=>setPage(number)}>{number}</button>)}{pages>5&&active<pages-2&&<span>… {pages}</span>}<button aria-label="Next records" disabled={active>=pages} onClick={()=>setPage(current=>current+1)}><ChevronRight size={16}/></button></nav></footer></section>;
}
