import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api/client.js';
import AsyncState from '../components/AsyncState.jsx';
import {formatTimestamp,labelize} from '../utils/display.js';
const routes={lead:'/sales/leads/',client:'/sales/clients/',proposal:'/sales/proposals/',invoice:'/finance/invoices/',event:'/events/events/'};
export default function AuditLog(){
 const [filters,setFilters]=useState({actor:'',action:'',entity:'',from:'',to:''}),[rows,setRows]=useState([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const result=await api.get('/audit-logs?'+new URLSearchParams({...Object.fromEntries(Object.entries(filters).filter(([,v])=>v)),page,pageSize:20}));setRows(result.data);setTotal(result.pagination.total);}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[filters,page]);
 return <main className="page"><div className="page-heading"><div><p className="eyebrow">Operational history</p><h1>Audit Log</h1><p className="lede">Who changed what, and when. Times use the business timezone.</p></div></div><div className="toolbar">{Object.keys(filters).map(key=><label key={key}>{labelize(key)}<input type={['from','to'].includes(key)?'date':'search'} value={filters[key]} onChange={e=>{setPage(1);setFilters(f=>({...f,[key]:e.target.value}));}}/></label>)}</div><AsyncState loading={loading} error={error} onRetry={load} noun="audit history">{!rows.length?<p>No matching changes.</p>:rows.map(row=><article className="panel audit-entry" key={row.id}><div className="audit-entry-summary"><p><strong>{row.actor_name}</strong> · {labelize(row.action)} · {labelize(row.entity)}</p><p>{routes[row.entity]&&row.entity_id?<Link to={routes[row.entity]+row.entity_id}>{row.target_label}</Link>:row.target_label}</p><time dateTime={row.created_at}>{formatTimestamp(row.created_at)}</time></div><details><summary>{row.changes.length} changed fields</summary>{row.changes.map(change=><p key={change.field}><strong>{labelize(change.field)}</strong>: {String(typeof change.before==='object'?JSON.stringify(change.before):change.before??'—')} → {String(typeof change.after==='object'?JSON.stringify(change.after):change.after??'—')}</p>)}<details><summary>Technical detail · secrets redacted</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify({before:row.before,after:row.after},null,2)}</pre></details></details></article>)}</AsyncState><div className="button-row"><button disabled={page<=1||loading} onClick={()=>setPage(p=>p-1)}>Previous page</button><span>Page {page} · {total} changes</span><button disabled={page*20>=total||loading} onClick={()=>setPage(p=>p+1)}>Next page</button></div></main>;
}
