import "../styles/event-planning.css";
import {useEffect,useState} from 'react';
import {api} from '../api/client.js';
import {useAuth} from '../context/AuthContext.jsx';
const blank={name:'',description:'',image_url:'',category:'CLASSIC',kind:'PHYSICAL',premium:false,upgrade_price:0,quantity:0,status:'INACTIVE',dimensions:'',notes:'',tags:[],display_order:0};
export default function Backdrops(){
 const {can}=useAuth();const [rows,setRows]=useState([]),[form,setForm]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
 async function load(){const data=await api.get('/backdrops');setRows(data.data);}
 useEffect(()=>{let active=true;api.get('/backdrops').then(data=>active&&setRows(data.data)).catch(e=>active&&setError(e.message));return()=>{active=false;};},[]);
 async function save(e){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const body=Object.fromEntries(Object.keys(blank).map(key=>[key,form[key]??blank[key]]));body.image_url=body.image_url||null;if(form.id)await api.patch('/backdrops/'+form.id,body);else await api.post('/backdrops',body);setForm(null);await load();setNotice('Backdrop saved. Archived backdrops remain in event history.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main className="page record-module"><div className="page-heading"><div><h1>Backdrops</h1><p className="lede">Manage the LOLA collection, stock and availability.</p></div>{can('write:operations')&&<button className="primary-action" onClick={()=>setForm({...blank})}>Add backdrop</button>}</div>{error&&<p role="alert" className="toast error">{error}</p>}{notice&&<p role="status">{notice}</p>}<label>Search collection<input value={search} onChange={e=>setSearch(e.target.value)}/></label><p>Reference entries start inactive until final images and physical stock are confirmed.</p><div className="planning-backdrops">{rows.filter(row=>row.name.toLowerCase().includes(search.toLowerCase())).map(row=><article className="panel" key={row.id}>{row.image_url&&<img src={row.image_url} alt={row.name} style={{width:'100%',maxHeight:220,objectFit:'cover'}}/>}<h2>{row.name}</h2><p>{row.category} · {row.kind} · {row.status}</p><p>{row.quantity} available units · {row.premium?'Premium $'+row.upgrade_price:'Included'}</p><p>{row.description}</p>{can('write:operations')&&<button onClick={()=>setForm({...row})}>Edit / archive</button>}</article>)}</div>{form&&<form className="panel" onSubmit={save}><h2>{form.id?'Edit backdrop':'New backdrop'}</h2>{['name','description','image_url','dimensions','notes','display_order','quantity','upgrade_price'].map(key=><label key={key}>{key.replaceAll('_',' ')}<input required={key==='name'} type={['display_order','quantity','upgrade_price'].includes(key)?'number':key==='image_url'?'url':'text'} min="0" value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}{[['category',['CLASSIC','GLAM','MODERN','FLORAL','CORPORATE']],['kind',['PHYSICAL','DIGITAL']],['status',['ACTIVE','INACTIVE','MAINTENANCE','ARCHIVED']]].map(([key,options])=><label key={key}>{key}<select value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}>{options.map(value=><option key={value}>{value}</option>)}</select></label>)}<label className="checkbox"><input type="checkbox" checked={form.premium} onChange={e=>setForm({...form,premium:e.target.checked})}/>Premium backdrop</label><div className="button-row"><button disabled={busy} className="primary-action">Save backdrop</button><button type="button" disabled={busy} onClick={()=>setForm(null)}>Cancel</button></div></form>}</main>;
}
