import {useEffect,useState} from 'react';
import {useParams} from 'react-router-dom';
import {formatDateOnly,formatMoney} from '../utils/display.js';
import '../styles/client-workspace.css';
import {Home,CalendarDays,Image,FileText,CreditCard} from 'lucide-react';
const API=window.location.hostname==='stagingadmin.thelolabooth.com'?'https://stagingapi.thelolabooth.com/api':import.meta.env.VITE_API_URL||'/api';
export default function ClientWorkspace(){
 const {token}=useParams();const [workspace,setWorkspace]=useState(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const controller=new AbortController();setError('');setWorkspace(null);
  fetch(`${API}/public/workspaces/${token}`,{signal:controller.signal}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error?.message||'Unable to open your event.');return data;}).then(data=>{if(!controller.signal.aborted)setWorkspace(data);}).catch(err=>{if(!controller.signal.aborted&&err.name!=='AbortError')setError(err.message);});
  return()=>controller.abort();
 },[token,refresh]);
 return <div className="secure-workspace"><aside className="workspace-sidebar"><img src="/brand/LOLA_Primary_Dark_Transparent.png" alt="The LOLA Booth"/><p className="workspace-motto">Good people.<br/>Better photos.</p><nav aria-label="Client workspace"><a className="workspace-nav-active" href="#workspace-home"><Home/>Home</a><a href="#event-details"><CalendarDays/>Event Details</a><a href="#planning"><Image/>Planning & Creative</a><a href="#agreement"><FileText/>Agreement</a><a href="#payments"><CreditCard/>Invoices & Payments</a><a href="#gallery"><Image/>Gallery</a></nav><div className="workspace-help"><strong>Need help?</strong><a href="mailto:info@thelolabooth.com">info@thelolabooth.com</a></div></aside><main id="workspace-home"><header><p className="eyebrow">Client Workspace</p><button onClick={()=>setRefresh(value=>value+1)}>Refresh</button></header>
  {error&&<p className="toast error" role="alert">{error}</p>}
  {!workspace&&!error&&<p role="status">Opening your event…</p>}
  {workspace&&<><h1>{workspace.event.name}</h1><p>{workspace.client} · {workspace.event.date?formatDateOnly(workspace.event.date):'Date to be confirmed'}{workspace.event.venue?` · ${workspace.event.venue}`:''}</p>
  <section className="workspace-card workspace-banner"><div><h2>Let’s bring your event to life.</h2><p>Complete a few quick steps to finalize your details.<br/>We’re here if you need anything.</p></div><img src="/staging-site/assets/hero-1.webp" alt="The LOLA Booth experience"/>{workspace.journey?.planning?.url?<a className="workspace-gold" href={workspace.journey.planning.url}>Continue Planning →</a>:<p>Planning opens once your booking is confirmed.</p>}</section><div className="workspace-card-grid"><section id="event-details" className="workspace-card"><h2><CalendarDays/>Event Details</h2><p>Review your date, location and booking.</p><dl><dt>Date</dt><dd>{formatDateOnly(workspace.event.date)}</dd><dt>Location</dt><dd>{workspace.event.venue||'To be confirmed'}</dd></dl></section>{workspace.journey&&<section id="planning" className="workspace-card"><h2><Image/>Creative & Backdrop</h2>{workspace.journey.planning?<><p>{workspace.journey.planning.status.replaceAll('_',' ')}</p><DocumentLink url={workspace.journey.planning.url} label="Event details, style, backdrop and uploads"/></>:<p>Your planning invitation will appear here once ready.</p>}<h3>Design and creative approval</h3>{workspace.journey.creative.length?workspace.journey.creative.map(proof=><article key={proof.id}><p>{proof.type} · Version {proof.version} · {proof.status.replaceAll('_',' ')}</p><DocumentLink url={proof.url} label="Review creative proof"/></article>):<p>Your creative proofs will appear here when ready for review.</p>}</section>}{workspace.proposal&&<section className="workspace-card"><h2><FileText/>Your Proposal</h2><p>{workspace.proposal.number} · {workspace.proposal.status}</p><p>Total {formatMoney(workspace.proposal.total)}</p><DocumentLink url={workspace.proposal.url} label="View proposal"/></section>}
  <section id="agreement" className="workspace-card"><h2><FileText/>Agreement</h2>{workspace.agreements.length?workspace.agreements.map(agreement=><article key={agreement.id}><h3>{agreement.title}</h3><p>Revision {agreement.revision} · {agreement.status==='SIGNED'?`Signed by ${agreement.signerName}`:'Ready for your signature'}</p><DocumentLink url={agreement.url} label={agreement.status==='SIGNED'?'View signed agreement':'Review and sign'}/></article>):<p>Your agreement will appear here when it is ready.</p>}</section>
  <section id="payments" className="workspace-card"><h2><CreditCard/>Payments</h2>{workspace.invoices.length?workspace.invoices.map(invoice=><article key={invoice.id}><h3>{invoice.number}</h3><p>{invoice.status} · Total {formatMoney(invoice.total)} · Balance {formatMoney(invoice.balance)}</p>{invoice.dueDate&&<p>Due {formatDateOnly(invoice.dueDate)}</p>}<DocumentLink url={invoice.url} label={invoice.balance>0?'View invoice and pay':'View invoice'}/></article>):<p>Your issued invoices will appear here.</p>}
  <details className="workspace-receipts"><summary>Payment Receipts ({workspace.receipts.length})</summary>{workspace.receipts.length?workspace.receipts.map(receipt=><article key={receipt.id}><p>{formatMoney(receipt.amount)} · {receipt.status.replaceAll('_',' ')}{receipt.date?` · ${formatDateOnly(receipt.date)}`:''}</p><DocumentLink url={receipt.url} label="View receipt"/></article>):<p>Your receipts will appear after payment is recorded.</p>}</details></section><section id="gallery" className="workspace-card"><h2><Image/>Gallery</h2><p>Your photos and videos will be available after the event.</p><span className="workspace-status">Available after event</span><p className="workspace-muted">Gallery delivery is part of the next release.</p></section></div><footer className="workspace-card workspace-footer"><p>Thank you for choosing The LOLA Booth.<br/><em>Good people. Better photos.</em></p><a href="https://thelolabooth.com/availability.html">Book Another Event →</a></footer></>}
 </main></div>;
}
function DocumentLink({url,label}){return url?<a className="primary-action" href={url} target="_blank" rel="noreferrer">{label}</a>:<p>This document link is unavailable. Contact The Lola Booth for access.</p>;}
