import "../styles/record-workspace.css";
import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api/client.js';
import AsyncState from '../components/AsyncState.jsx';
import StatusBadge from '../components/StatusBadge.jsx';
import {formatTimestamp} from '../utils/display.js';
export default function Integrations(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('');
 async function load(){setError('');try{setData((await api.get('/integrations/catalog')).data);}catch(e){setError(e.message);}}
 useEffect(()=>{load();},[]);
 async function test(provider){if(busy)return;setBusy(provider);setError('');try{const result=await api.post(`/integrations/${provider}/local-test`,{});setNotice(result.message);await load();}catch(e){setError(e.message);}finally{setBusy('');}}
 async function disable(provider){if(busy)return;setBusy(provider);setError('');setNotice('');try{await api.patch(`/integrations/${provider}`,{status:'DISCONNECTED'});setNotice(`${provider} disabled.`);await load();}catch(e){setError(e.message);}finally{setBusy('');}}
 return <main className="page integrations-redesign record-module"><div className="page-heading"><div><p className="eyebrow">System</p><h1>Integrations</h1><p className="lede">Connect your tools and services to streamline your workflow.</p></div><button onClick={load}>Refresh</button></div>{notice&&<p role="status" className="toast">{notice}</p>}<AsyncState loading={!data&&!error} error={error} onRetry={load} noun="integrations">{data&&<><div className="toolbar"><label>Search integrations<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search integrations…"/></label></div><div className="lola-status-tabs">{['','CONNECTED','AVAILABLE'].map(value=><button key={value||'all'} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{value||'All'}</button>)}</div></>}{data&&['Communications' ,'Payments','Marketing & Analytics','Website'].map(group=><section className="integration-section" key={group}><h2>{group}</h2><div className="integration-grid">{data.filter(x=>x.group===group&&`${x.label} ${x.detail}`.toLowerCase().includes(search.toLowerCase())&&(!filter||(filter==='CONNECTED'?x.status==='CONNECTED':x.status!=='CONNECTED'))).map(card=><article className="panel integration-card" key={card.provider}><div className="integration-heading"><span className="integration-provider-icon" aria-hidden="true">{card.label.slice(0,1)}</span><div><h3>{card.label}</h3><small>{card.detail}</small></div><StatusBadge status={card.status}/></div><details className="integration-manage"><summary>Manage</summary><p><strong>Mode:</strong> {card.mode}</p><p>{card.detail}</p>{card.counts&&<p>Queued: {card.counts.queued} · Mock completed: {card.counts.mock_completed} · Provider completed: {card.counts.provider_completed}</p>}<dl><dt>Configuration</dt><dd>{card.config.required?`${card.config.present} of ${card.config.required} fields present`:'No credentials required for this local status'}</dd><dt>Last payload test</dt><dd>{card.lastTest?formatTimestamp(card.lastTest):'Not tested'}</dd><dt>Last successful activity</dt><dd>{card.lastSuccess?formatTimestamp(card.lastSuccess):'Not verified'} · {card.evidenceMode}</dd><dt>Last failed job</dt><dd>{card.lastFailure?formatTimestamp(card.lastFailure):'None recorded'}</dd></dl><div className="button-row">
  {card.config.required>0&&<Link className="table-action" to="/system/settings#integrations">{card.stateManaged&&card.connectionStatus==="DISCONNECTED"?"Reconnect / Configure":["NOT_CONFIGURED","ERROR","DISABLED"].includes(card.status)?"Configure":"Review configuration"}</Link>}
  <button className="table-action" disabled={Boolean(busy)} onClick={load}>Recheck status</button>
  {card.testAvailable&&<button disabled={Boolean(busy)} onClick={()=>test(card.provider)}>{busy===card.provider?'Testing…':card.provider==='STRIPE'?'Check test configuration':`Test ${card.provider==='META'?'Meta':card.provider==='TIKTOK'?'TikTok':'GA4'} Payload`}</button>}
  {card.stateManaged&&card.connectionStatus!=="DISCONNECTED"&&<button disabled={Boolean(busy)} onClick={()=>disable(card.provider)}>{busy===card.provider?"Working…":"Disable"}</button>}
</div>
{["PENDING_VERIFICATION","PENDING_APPROVAL","TEST_READY"].includes(card.status)&&<p className="note-text">Configuration is not the same as verified provider connectivity. Complete the provider-specific verification before treating this integration as live.</p>}
{card.provider==="LINKEDIN"&&card.status==="PENDING_APPROVAL"&&<p className="note-text">LinkedIn Lead Sync requires LinkedIn API approval. Setup has been initiated, but external delivery is not verified yet.</p>}
<details><summary>Configuration guidance</summary><p>Credentials belong in the server environment, never in this browser.</p>{card.config.fields.length>0&&<ul>{card.config.fields.map(key=><li key={key}>{key}</li>)}</ul>}<Link to="/system/settings#integrations">Open integration preferences</Link></details></details></article>)}</div></section>)}</AsyncState><InboundHistory/></main>;
}

function InboundHistory(){
 const [data,setData]=useState(null),[error,setError]=useState('');
 async function load(){try{setData(await api.get('/integrations/overview'));}catch(e){setError(e.message);}}
 useEffect(()=>{load();},[]);
 async function retry(id){try{await api.post(`/integrations/failed-inbound/${id}/retry`,{});await load();}catch(e){setError(e.message);}}
 return <section className="panel"><h2>Lead Sources</h2><p>Inbound forms, field mappings and delivery history appear here after a provider has been configured. Provider approval requirements are shown on the integration card above.</p>{error&&<p role="alert">{error}</p>}{data?.leadSources?.map(source=><details key={source.provider}><summary>{source.provider} · {source.leads_received_count||0} leads received</summary><p>Last successful lead: {source.last_successful_lead_at?formatTimestamp(source.last_successful_lead_at):'None'}</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(source.fieldMaps||[],null,2)}</pre></details>)}<h3>Failed inbound leads</h3>{data?.failedInbound?.length?data.failedInbound.map(item=><p key={item.id}>{item.provider} · {item.status} <button onClick={()=>retry(item.id)}>Retry inbound event</button></p>):<p>No failed inbound events.</p>}</section>;
}
