import {loadCatalog} from "../../shared/catalog-loading.js";
import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api/client.js';
import {proposalEventTypes} from '../../shared/proposal-scenario.js';
export default function ProposalTemplates(){
  const [record,setRecord]=useState(null),[config,setConfig]=useState(null),[group,setGroup]=useState('global'),[key,setKey]=useState('Wedding'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[packages,setPackages]=useState([]),[assets,setAssets]=useState([]);
  useEffect(()=>{let active=true;Promise.all([api.get('/proposal-scenario-template'),loadCatalog(api.get,'packages'),api.get('/proposal-assets')]).then(([r,p,a])=>{if(active){setRecord(r);setConfig(r.config);setPackages(p);setAssets(a.data||[]);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
  async function save(){setBusy(true);setError('');setNotice('');try{const row=await api.patch('/proposal-scenario-template',{version:record.version,config});setRecord(row);setNotice('Proposal defaults saved. Existing proposals keep their snapshots.');}catch(e){setError(e.message);}finally{setBusy(false);}}
  if(!config)return <main className="page"><h1>Proposal defaults</h1><p role="alert">{error||'Loading defaults…'}</p></main>;
  const values=group==='global'?config.global:config[group]?.[key]||{};
  const update=(field,value)=>setConfig(current=>group==='global'?{...current,global:{...current.global,[field]:value}}:{...current,[group]:{...current[group],[key]:{...current[group]?.[key],[field]:value}}});
  const choices=group==='events'?proposalEventTypes:group==='experiences'?['glam','360','vogue','audio']:packages.map(p=>p.id);
  return <main className="page"><Link to="/system/settings">← Settings</Link><div className="page-heading"><div><h1>Proposal defaults</h1><p>Global → event → experience & package → individual proposal. Merge variables such as {'{{event_name}}'} are resolved when a proposal is built.</p></div><button className="primary-action" disabled={busy} onClick={save}>{busy?'Saving…':'Save defaults'}</button></div>{error&&<p role="alert" className="toast error">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <div className="form-grid"><label>Layer<select value={group} onChange={e=>{setGroup(e.target.value);setKey(e.target.value==='events'?'Wedding':e.target.value==='experiences'?'glam':packages[0]?.id||'');}}>{['global','events','experiences','packages'].map(g=><option key={g} value={g}>{g}</option>)}</select></label>{group!=='global'&&<label>Scenario<select value={key} onChange={e=>setKey(e.target.value)}>{choices.map(k=><option key={k} value={k}>{packages.find(p=>p.id===k)?.name||k}</option>)}</select></label>}</div>
    {group==='packages'&&<p>Package inclusions, duration and price are maintained in <Link to="/content/packages">Packages</Link>. Use this layer for a reusable package description only.</p>}
    <section className="wizard-panel"><div className="form-grid">{Object.entries(values).filter(([field,value])=>typeof value==='string' && field!=='tone').map(([field,value])=><label key={group+key+field}>{field.replaceAll('_',' ')}<textarea rows={5} value={value} onChange={e=>update(field,e.target.value)}/></label>)}{group==='packages'&&<label>Package description<textarea value={values.description||''} onChange={e=>update('description',e.target.value)}/></label>}
      {group!=='packages'&&<><label>Approved default imagery<select value={values.media_ids?.[0]||''} onChange={e=>update('media_ids',e.target.value?[e.target.value]:[])}><option value="">Use next fallback layer</option>{assets.map(a=><option key={a.id} value={a.id}>{a.alt_text||a.filename||a.id}</option>)}</select></label>{['next_steps','goals'].map(field=>(values[field]||group==='global')&&<label key={field}>{field.replaceAll('_',' ')} (one per line)<textarea rows={6} value={(values[field]||[]).join('\n')} onChange={e=>update(field,e.target.value.split('\n').filter(Boolean))}/></label>)}{(values.why_items||group==='global')&&<label>Why LOLA highlights (title | description)<textarea rows={8} value={(values.why_items||[]).map(i=>i.title+' | '+i.body).join('\n')} onChange={e=>update('why_items',e.target.value.split('\n').filter(Boolean).map((line,index)=>{const [title,...body]=line.split('|');return{icon:values.why_items?.[index]?.icon||'diamond',title:title.trim(),body:body.join('|').trim()};}))}/></label>}</>}
    </div></section>
  </main>;
}
