import {useEffect,useRef,useState} from 'react';
import {useParams} from 'react-router-dom';
const host=window.location.hostname;
const API=host==='stagingadmin.thelolabooth.com'?'https://stagingapi.thelolabooth.com/api':host==='admin.thelolabooth.com'?'https://api.thelolabooth.com/api':import.meta.env.VITE_API_URL||'/api';
export default function PublicCreativeApproval(){
 const {token,eventId,approvalId}=useParams();const csrf=useRef(null);const base=eventId?`${API}/public/client/events/${eventId}/creative/${approvalId}`:`${API}/public/approvals/${encodeURIComponent(token)}`; const [proof,setProof]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState({name:'',email:'',notes:''});
 async function request(suffix='',options={}){if(eventId&&!csrf.current){const response=await fetch(API+'/public/client/session',{credentials:'include'});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||'Sign in to continue.');csrf.current=data.csrfToken;setForm(current=>({...current,email:data.email}));}const response=await fetch(base+suffix,{...options,...(eventId?{credentials:'include',headers:{...options.headers,'X-Client-CSRF':csrf.current}}:{})});const result=await response.json();if(!response.ok)throw new Error(result.error?.message||'Unable to open this design.');return result.approval;}
 useEffect(()=>{let active=true;setProof(null);setError('');request().then(value=>active&&setProof(value)).catch(e=>active&&setError(e.message));return()=>{active=false;};},[token,eventId,approvalId]);
 async function respond(event){event.preventDefault();if(busy)return;const action=event.nativeEvent.submitter?.value;if(!action)return;setBusy(true);setError('');try{setProof(await request('/respond',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,action,version:proof.version})}));}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main className="public-document agreement-page"><article className="panel"><img src="/brand/LOLA_Primary_Dark_Transparent.png" width="140" alt="The LOLA Booth"/><h1>Your LOLA design</h1>{error&&<p role="alert" className="toast error">{error}</p>}{!proof&&!error&&<p role="status">Opening your design…</p>}{proof&&<><p>Version {proof.version} · {proof.approval_type}</p>{proof.hasDocument?<p><a href={base+'/proof'}>Download and review your proof</a></p>:proof.proof_url?.startsWith('https://')?<p><a href={proof.proof_url} target="_blank" rel="noopener noreferrer">Open your design</a></p>:<p>Contact LOLA for your design proof.</p>}{proof.status==='APPROVED'?<section role="status"><h2>Design approved</h2><p>Version {proof.approved_version} is your approved production version. Thank you!</p></section>:proof.status==='CHANGES_REQUESTED'?<p role="status">Your changes have been sent to LOLA. We’ll share a new version for review.</p>:<form onSubmit={respond}><p>Review this version before responding. Use the email associated with your event.</p><label>Full name <span aria-label="required">*</span><input required autoComplete="name" maxLength={160} minLength={2} disabled={busy} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email <span aria-label="required">*</span><input required type="email" autoComplete="email" maxLength={160} disabled={busy} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Changes or comments<textarea maxLength={3000} disabled={busy} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="button-row"><button className="primary-action" name="action" value="approve" disabled={busy}>Approve design</button><button name="action" value="request_changes" disabled={busy||!form.notes.trim()}>Request changes</button></div></form>}</>}</article></main>;
}
