import {useEffect,useState} from 'react';
import {useParams} from 'react-router-dom';
import SignaturePad from '../components/SignaturePad.jsx';
import {DRAWN_CONTRACT_CONSENT,validDrawnSignature} from '../../shared/signature.js';
import '../styles/client-agreement.css';
import {CONTRACT_CONSENT} from '../../shared/contracts.js';
const API=window.location.hostname==='stagingadmin.thelolabooth.com'?'https://stagingapi.thelolabooth.com/api':import.meta.env.VITE_API_URL||'/api';
async function request(path,options={}){const response=await fetch(`${API}/public/contracts/${path}`,options);const data=await response.json();if(!response.ok)throw new Error(data.error?.message||'Unable to open this agreement.');return data;}
export default function PublicContract(){
 const {token}=useParams();const [method,setMethod]=useState('TYPED'),[strokes,setStrokes]=useState([]);const [contract,setContract]=useState(null),[error,setError]=useState(''),[name,setName]=useState(''),[email,setEmail]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{let current=true;setContract(null);setError('');setName('');setEmail('');setConsent(false);request(token).then(data=>{if(current){setContract(data);setEmail(data.snapshot.client_email);}}).catch(err=>current&&setError(err.message));return()=>{current=false;};},[token]);
 async function sign(e){e.preventDefault();if(busy)return;if(!consent){setError('Please check that you have read and agree to the agreement before signing.');return;}setBusy(true);setError('');try{setContract(await request(`${token}/sign`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,consent,documentHash:contract.document_hash,signatureMethod:method,...(method==='DRAWN'?{signatureStrokes:strokes}:{})})}));}catch(err){setError(err.message);}finally{setBusy(false);}}
 return <main className="public-document agreement-page"><article className="panel"><img src="/brand/LOLA_Primary_Dark_Transparent.png" alt="The Lola Booth" width="140"/><p className="eyebrow">Client agreement</p>
 {error&&<p role="alert" className="toast error">{error}</p>}
 {!contract&&!error&&<p role="status">Opening your agreement…</p>}
 {contract&&new URLSearchParams(window.location.search).get('download')==='pdf'&&<p><a href={`${API}/public/contracts/${token}/pdf`}>Download your agreement PDF</a></p>}
 {contract&&<>{contract.signing_due_at&&contract.status!=='SIGNED'&&<p className="agreement-deadline">Please sign by {new Date(contract.signing_due_at).toLocaleDateString()} to complete your booking.</p>}<div className="agreement-layout"><section className="agreement-document"><h1>{contract.title}</h1><p>{contract.snapshot.proposal_number} · Revision {contract.revision}</p>
 {Array.isArray(contract.snapshot.items)&&contract.snapshot.items.length>0&&<section className="panel"><h2>Selected services</h2><ul>{contract.snapshot.items.map((item,index)=><li key={index}>{item.description||item.label||'Service'} · {item.quantity??1} × {item.unit_price??item.amount??''}</li>)}</ul></section>}
 <h2>Service terms</h2><div className="agreement-terms">{contract.terms}</div>
 </section><aside className="agreement-signing"><section className="panel"><h2>Event Summary</h2><dl>{[['Client',contract.snapshot.client_name],['Event',contract.snapshot.event_name],['Date',contract.snapshot.event_date],['Venue',contract.snapshot.venue_name],['Total',contract.snapshot.total]].filter(([,v])=>v!=null).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{contract.snapshot.payment_exception&&<p>Approved payment arrangement: {contract.snapshot.payment_exception.reason}. Balance due {contract.snapshot.payment_exception.balance_due_date}.</p>}</section>
 {contract.status==='SIGNED'?<section className="panel" role="status"><h2>Agreement signed</h2><p>{contract.signer_name} · {new Date(contract.signed_at).toLocaleString()}</p><p>{contract.consent_text}</p>{contract.booking_confirmation&&<p>{contract.booking_confirmation.status==='CONFIRMED'?'Your booking is confirmed. Open The Client Workspace to continue Planning & Creative.':contract.booking_confirmation.message||'Your booking confirmation is awaiting LOLA review.'}</p>}</section>:<form onSubmit={sign}><h2>Sign your agreement</h2><label>Full legal name <span className="required-mark" aria-hidden="true">*</span><input autoComplete="name" required minLength={2} maxLength={200} disabled={busy} value={name} onChange={e=>setName(e.target.value)}/></label><label>Client email <span className="required-mark" aria-hidden="true">*</span><input type="email" autoComplete="email" required disabled={busy} value={email} onChange={e=>setEmail(e.target.value)}/></label><fieldset><legend>Choose your signature style</legend><button type="button" aria-pressed={method==='TYPED'} disabled={busy} onClick={()=>setMethod('TYPED')}>Type</button><button type="button" aria-pressed={method==='DRAWN'} disabled={busy} onClick={()=>setMethod('DRAWN')}>Draw</button></fieldset>{method==='DRAWN'?<SignaturePad strokes={strokes} onChange={setStrokes} disabled={busy}/>:<p className="typed-signature" aria-label="Typed signature preview">{name||'Your signature'}</p>}<label className="agreement-consent"><input type="checkbox" required aria-describedby="agreement-signing-help" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/><span><strong>I have read and agree to the terms of this Agreement. <span className="required-mark" aria-hidden="true">*</span></strong><span>{method==='DRAWN'?DRAWN_CONTRACT_CONSENT:CONTRACT_CONSENT}</span></span></label><p id="agreement-signing-help" className="agreement-signing-help" role="status">{!consent?'Check the agreement box above to enable signing.':method==='DRAWN'&&!validDrawnSignature(strokes)?'Draw your signature above to enable signing.':'Provide your full legal name and email, then sign your agreement.'}</p><button className="primary-action" disabled={busy||!consent||(method==='DRAWN'&&!validDrawnSignature(strokes))}>{busy?'Signing…':'Sign agreement'}</button></form>}
 <p><a href={`${API}/public/contracts/${token}/pdf`}>Download {contract.status==='SIGNED'?'signed copy':'agreement'} PDF</a></p><p><a href="/client">Return to The Client Workspace →</a></p><p className="note-text">Signing this agreement does not process a payment. Your booking is confirmed after accepted terms, required payment, agreement signing and availability checks.</p></aside></div></>}
 </article></main>;
}
