import {useEffect,useRef,useState} from 'react';
import {useParams} from 'react-router-dom';
import {PLANNING_MOODS,PLANNING_EVENT_FIELDS,PLANNING_EXTRA_FIELDS,missingPlanningFields} from '../../shared/event-planning.js';
import '../styles/event-planning.css';
import ClientBackdropQuote from '../components/ClientBackdropQuote.jsx';
const host=window.location.hostname;
const API=host==='stagingadmin.thelolabooth.com'?'https://stagingapi.thelolabooth.com/api':host==='admin.thelolabooth.com'?'https://api.thelolabooth.com/api':import.meta.env.VITE_API_URL||'/api';
const steps=['Event Details','Your Style','Backdrop','Uploads','Review'];
const fields=[['event_name','Event name'],['event_type','Event type'],['event_date','Event date','date'],['start_time','Start time','time'],['end_time','End time','time'],['guest_count','Guest count','number'],['venue_name','Venue name'],['venue_address','Venue address'],['primary_contact_name','Primary contact name'],['primary_contact_email','Primary contact email','email'],['primary_contact_phone','Primary contact phone','tel'],['on_site_contact_name','On-site contact name'],['on_site_contact_phone','On-site contact phone','tel'],['setup_instructions','Setup / loading instructions'],['parking_instructions','Parking instructions'],['notes','Special requests / notes']];
export default function PublicEventPlanning(){
 const {token}=useParams();const [data,setData]=useState(null),[brief,setBrief]=useState({}),[step,setStep]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[category,setCategory]=useState('ALL'),[preview,setPreview]=useState(null),[attempted,setAttempted]=useState(false),[focusField,setFocusField]=useState(null);const page=useRef(null),lock=useRef(false),uploadInput=useRef(null),previewDialog=useRef(null);
 const base=API+'/public/planning/'+encodeURIComponent(token);
 async function request(suffix='',options={}){const response=await fetch(base+suffix,{...options,headers:{'Content-Type':'application/json',...options.headers}});const result=await response.json();if(!response.ok){const failure=new Error(result.error?.message||'Unable to save your event.');failure.details=result.error?.details;throw failure;}return result;}
 useEffect(()=>{let active=true;setData(null);setError('');setAttempted(false);setFocusField(null);request().then(result=>{if(active){setData(result);setBrief(result.brief);}}).catch(e=>active&&setError(e.message));return()=>{active=false;};},[token]);
 useEffect(()=>{if(preview&&previewDialog.current&&!previewDialog.current.open)previewDialog.current.showModal();},[preview]);
 async function run(action){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await action();}catch(e){if(Array.isArray(e.details)){const fields=e.details.map(issue=>issue.path?.at(-1)).filter(Boolean);setError('Please check: '+fields.map(key=>PLANNING_EVENT_FIELDS[key]||PLANNING_EXTRA_FIELDS[key]||key.replaceAll('_',' ')).join(', '));}else{setError(e.message);}if(e.details?.missing?.length){setAttempted(true);jump(e.details.missing[0]);}}finally{lock.current=false;setBusy(false);}}
 async function save(next){const saved=await request('',{method:'PATCH',body:JSON.stringify({brief})});setData(saved);setNotice('Progress saved. Return anytime using this link.');if(next!=null)setStep(next);return saved;}
 function change(key,value){setBrief(current=>({...current,[key]:value}));}
 async function choose(path,id){await run(async()=>{setData(await request('/backdrop',{method:'POST',body:JSON.stringify({path,...(id?{backdrop_id:id}:{})})}));setNotice('Backdrop choice saved for LOLA review. Premium and custom charges require confirmation.');});}
 async function upload(files){await run(async()=>{for(const file of Array.from(files||[])){if(file.size>8*1024*1024)throw new Error('Each file must be 8 MB or smaller.');const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Unable to read file.'));reader.readAsDataURL(file);});await request('/assets',{method:'POST',body:JSON.stringify({filename:file.name,mime_type:file.type,base64})});}setData(await request());setNotice('Your files were uploaded privately.');});if(uploadInput.current)uploadInput.current.value='';}
 const missing=data?missingPlanningFields(brief,data.requirements,Boolean(data.backdrop_id||['OWN','CUSTOM'].includes(data.backdrop_path)),data.assets.length):[];
 function jump(item){setStep(item.step);setFocusField(item.key);}
 useEffect(()=>{if(focusField&&!busy){const target=page.current?.querySelector(`[data-planning-field="${focusField}"]`);target?.focus();target?.scrollIntoView({block:'center'});setFocusField(null);}},[step,focusField,busy]);
 function input(key,label,type='text'){const required=(data?.requirements.includes('event_details')&&key in PLANNING_EVENT_FIELDS)||data?.requirements.includes(key);const issue=attempted?missing.find(item=>item.key===key):null;return <label key={key}>{label}{required&&<span className="planning-required" aria-label="required"> *</span>}<input id={'planning-'+key} data-planning-field={key} type={type} required={required} aria-invalid={Boolean(issue)} aria-describedby={issue?'planning-error-'+key:undefined} disabled={busy} value={brief[key]??''} min={type==='number'?0:undefined} onChange={e=>change(key,type==='number'?Number(e.target.value):e.target.value)}/>{issue&&<span id={'planning-error-'+key} className="planning-field-error">{issue.message}</span>}</label>;}
 async function submit(){setAttempted(true);if(missing.length){setError('Complete the listed required fields before submitting. Your answers are preserved.');jump(missing[0]);return;}await save();setData(await request('/submit',{method:'POST'}));}
 const selected=data?.backdrops.find(row=>row.id===data.backdrop_id);
 return <main ref={page} className="client-planning-page"><header><img src="/brand/LOLA_Primary_Dark_Transparent.png" width="140" alt="The LOLA Booth"/>{data&&!['SUBMITTED','APPROVED','COMPLETE'].includes(data.status)&&<button disabled={busy} onClick={()=>run(()=>save())}>Save & continue later</button>}</header><ClientBackdropQuote base={base}/>{error&&<p role="alert" className="planning-error">{error}</p>}{data&&missing.length>0&&(attempted||step===4)&&<section className="planning-validation" aria-label="Required fields to complete"><h2>Still to complete</h2><ul>{missing.map(item=><li key={item.key}><button disabled={busy} onClick={()=>jump(item)}>{item.label}: {item.message}</button></li>)}</ul></section>}{notice&&<p role="status" className="planning-notice">{notice}</p>}{!data&&!error&&<p role="status">Opening your event…</p>}{data&&(['SUBMITTED','APPROVED','COMPLETE'].includes(data.status)?<section className="planning-card"><h1>You’re all set!</h1><p>We’ve received your event details. The LOLA team will review everything and begin preparing your experience. We’ll let you know when your design is ready for approval.</p></section>:<><nav aria-label="Planning steps">{steps.map((name,index)=><button key={name} disabled={busy} aria-current={index===step?'step':undefined} onClick={()=>run(()=>save(index))}><span>{index+1}</span>{name}</button>)}</nav><section className="planning-card"><h1>{['Let’s start with the basics','Make it yours','Choose your backdrop','Your logos & inspiration','Review your event details'][step]}</h1>
 {step===0&&<><p>We’ve filled in what we know. Date, time and venue changes will be requests for LOLA review.</p><p><span className="planning-required">*</span> Required to submit. You can save incomplete answers and return later.</p><div className="planning-fields">{fields.map(([key,label,type])=>input(key,label,type))}</div></>}
 {step===1&&<><fieldset><legend>What’s the vibe?</legend><div className="planning-moods">{PLANNING_MOODS.map(mood=><button key={mood} disabled={busy} aria-pressed={brief.moods?.includes(mood)||false} onClick={()=>change('moods',brief.moods?.includes(mood)?brief.moods.filter(value=>value!==mood):[...(brief.moods||[]),mood])}>{mood}</button>)}</div></fieldset>{input('theme','Event theme')}<fieldset><legend>Event colors{data.requirements.includes('colors')&&<span className="planning-required" aria-label="required"> *</span>}</legend>{(brief.colors||[]).map((color,index)=><div className="planning-color" key={index}><label>Color {index+1}<input disabled={busy} type="color" value={/^#[a-fA-F0-9]{6}$/.test(color)?color:'#000000'} onChange={e=>change('colors',brief.colors.map((value,i)=>i===index?e.target.value:value))}/></label><label>HEX<input disabled={busy} value={color} pattern="#[a-fA-F0-9]{6}" maxLength={7} onChange={e=>change('colors',brief.colors.map((value,i)=>i===index?e.target.value:value))}/></label><button disabled={busy||index===0} aria-label={'Move color '+(index+1)+' earlier'} onClick={()=>{const colors=[...brief.colors];[colors[index-1],colors[index]]=[colors[index],colors[index-1]];change('colors',colors);}}>↑</button><button disabled={busy} onClick={()=>change('colors',brief.colors.filter((_,i)=>i!==index))}>Remove</button></div>)}<button data-planning-field="colors" disabled={busy||(brief.colors?.length||0)>=12} onClick={()=>change('colors',[...(brief.colors||[]),'#d4af37'])}>Add color</button></fieldset><label>Anything we should know about the look you’re going for?<textarea maxLength={3000} value={brief.creative_notes||''} onChange={e=>change('creative_notes',e.target.value)}/></label>{[['music','Music preference'],['environment','Background / environment'],['display_messaging','Display messaging'],['greeting','Audio guestbook greeting / script'],['phone_placement','Phone placement'],['signage','Signage instructions']].filter(([key])=>data.requirements.includes(key)).map(([key,label])=>input(key,label))}</>}
 {step===2&&<><p>{data.requirements.includes('backdrop')?<strong>Backdrop choice is required. </strong>:null}Choose a collection backdrop, upload your own artwork or request a custom design. Custom design is subject to review and a confirmed quote.</p><div className="button-row">{[['OWN','Upload your own'],['CUSTOM','Request custom design']].map(([path,label])=><button key={path} data-planning-field={path==='OWN'?'backdrop':undefined} disabled={busy} aria-pressed={data.backdrop_path===path} onClick={()=>choose(path)}>{label}</button>)}</div>{data.backdrop_path&&data.backdrop_path!=='COLLECTION'&&<p>{data.backdrop_path==='OWN'?'Upload your artwork in Uploads.':'Describe your custom request in Your Style and add inspiration in Uploads.'}</p>}<div className="planning-moods">{['ALL','CLASSIC','GLAM','MODERN','FLORAL','CORPORATE'].map(value=><button key={value} aria-pressed={category===value} onClick={()=>setCategory(value)}>{value}</button>)}</div><div className="planning-backdrops">{data.backdrops.filter(row=>category==='ALL'||row.category===category).map(row=><article key={row.id} className={data.backdrop_id===row.id?'selected':''}>{row.image_url?<button className="backdrop-preview" onClick={()=>setPreview(row)} aria-label={'Preview '+row.name}><img src={row.image_url} alt={row.name}/></button>:<div className="backdrop-placeholder">Image pending</div>}<h2>{row.name}</h2><p>{row.description}</p><p>{row.premium?'Premium · $'+row.upgrade_price:'Included'} · {row.status}</p><button disabled={busy||row.status!=='ACTIVE'} onClick={()=>choose('COLLECTION',row.id)}>Select this backdrop</button></article>)}</div>{!data.backdrops.length&&<p>LOLA is confirming collection availability. Request a custom design or ask LOLA about your backdrop.</p>}</>}
 {step===3&&<><p>{data.requirements.includes('assets')&&'Upload a file or choose “No logos or other assets are needed.” '}PNG, JPG and PDF · maximum 8 MB each. Logos, monograms, photos, brand guides and inspiration remain private.</p><div className="planning-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)upload(e.dataTransfer.files);}}><label>Upload files{data.requirements.includes('assets')&&<span className="planning-required" aria-label="required"> *</span>}<input data-planning-field="assets" ref={uploadInput} type="file" accept="image/png,image/jpeg,application/pdf" multiple disabled={busy} onChange={e=>upload(e.target.files)}/></label><p>Or drop files here.</p></div>{data.assets.map(file=><p key={file.id}><a href={base+'/assets/'+file.id}>{file.filename}</a></p>)}<label className="planning-check"><input type="checkbox" checked={brief.assets_not_required||false} onChange={e=>change('assets_not_required',e.target.checked)}/>No logos or other assets are needed.</label><label>Optional HTTPS asset links · one per line<textarea value={(brief.external_links||[]).join('\n')} onChange={e=>change('external_links',e.target.value.split('\n').filter(Boolean).slice(0,10))}/></label></>}
 {step===4&&<>{[['Your event',0,brief.event_name+' · '+brief.event_date+' · '+brief.venue_name],['Your style',1,(brief.theme||'No theme')+' · '+(brief.moods||[]).join(', ')],['Your backdrop',2,selected?.name||data.backdrop_path||'Not selected'],['Your assets',3,data.assets.map(file=>file.filename).join(', ')||'No files'],['Your notes',1,brief.creative_notes||brief.notes||'No notes']].map(([title,index,value])=><section className="planning-summary" key={title}><h2>{title}</h2><p>{value}</p><button onClick={()=>setStep(index)}>Edit</button></section>)}{Object.keys(data.change_requests||{}).length>0&&<p>Requested booking changes are pending LOLA review. Your confirmed booking remains as agreed.</p>}<p>LOLA will confirm any premium or custom charges before applying them.</p></>}
 <footer><button disabled={busy||step===0} onClick={()=>run(()=>save(step-1))}>Back</button>{step<4?<button className="planning-primary" disabled={busy} onClick={()=>run(()=>save(step+1))}>Continue to {steps[step+1]} →</button>:<button className="planning-primary" disabled={busy} onClick={()=>run(submit)}>Submit event details</button>}</footer></section></>)}{preview&&<dialog ref={previewDialog} onCancel={()=>setPreview(null)} className="planning-image-dialog"><button onClick={()=>setPreview(null)}>Close preview</button><img src={preview.image_url} alt={preview.name}/><h2>{preview.name}</h2><button onClick={()=>{choose('COLLECTION',preview.id);setPreview(null);}}>Select this backdrop</button></dialog>}</main>;
}
