import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api/client.js';
import {useAuth} from '../context/AuthContext.jsx';
import AsyncState from '../components/AsyncState.jsx';
import DataTable from '../components/DataTable.jsx';
import StatusBadge from '../components/StatusBadge.jsx';
import RelationshipSelect from '../components/RelationshipSelect.jsx';
export default function Roster({kind}){
 const staff=kind==='staff',title=staff?'Staff':'Equipment';const {can}=useAuth();
 const [rows,setRows]=useState([]),[search,setSearch]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[editing,setEditing]=useState(null),[detail,setDetail]=useState(null),[form,setForm]=useState({});
 async function load(){setLoading(true);setError('');try{const r=await api.get(`/${kind}?pageSize=100&search=${encodeURIComponent(search)}`);setRows(r.data);}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{setDetail(null);setEditing(null);load();},[kind,search]);
 async function view(row){try{setDetail(await api.get(`/${kind}/${row.id}`));}catch(e){setError(e.message);}}
 function edit(row={}){setForm({...row,name:row.name||'',category:row.category||'',email:row.email||'',phone:row.phone||'',role:row.role||'ATTENDANT',active:row.active??true,status:row.status||'AVAILABLE',notes:row.notes||'',unavailable:(row.availability?.unavailable_dates||[]).join('\n')});setEditing(row.id||'new');setError('');}
 async function save(e){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const body=staff?{name:form.name,email:form.email||null,phone:form.phone||null,role:form.role,active:form.active,notes:form.notes,user_id:form.user_id||null,availability:{unavailable_dates:form.unavailable.split(/\s+/).filter(Boolean)}}:{name:form.name,category:form.category,status:form.status,serial_number:form.serial_number||null,...(form.asset_uid?{asset_uid:form.asset_uid}:{})};const saved=editing==='new'?await api.post(`/${kind}`,body):await api.patch(`/${kind}/${editing}`,body);setEditing(null);await load();await view(saved);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main className="page"><div className="page-heading"><div><p className="eyebrow">Operations</p><h1>{title}</h1><p className="lede">{staff?'Manage people, availability and event assignments.':'Manage assets, service status and assignment history.'}</p></div>{can('write:events')&&<button className="primary-action" onClick={()=>edit()}>Create {staff?'staff member':'equipment'}</button>}</div><label>Search {title.toLowerCase()}<input value={search} onChange={e=>setSearch(e.target.value)}/></label><AsyncState loading={loading} error={!editing&&error} onRetry={load} noun={title.toLowerCase()}>{!loading&&<div className="roster-grid">{rows.map(row=><article className="panel" key={row.id}><h2>{row.name}</h2><StatusBadge status={staff?(row.active?'ACTIVE':'INACTIVE'):row.status}/><p>{staff?row.role:row.asset_uid||row.serial_number||'Asset code not assigned'}</p><p>{staff?row.email:row.category}</p><div className="button-row"><button onClick={()=>view(row)}>View history</button>{can('write:events')&&<button onClick={()=>edit(row)}>Edit</button>}</div></article>)}{!rows.length&&<AsyncState empty noun={title.toLowerCase()}/>}</div>}</AsyncState>
 {detail&&<section className="panel"><div className="table-heading"><h2>{detail.name} · assignments and history</h2><button onClick={()=>setDetail(null)}>Close history</button></div><p>Open an event to manage assignment, {staff?'acknowledgment or decline':'checkout or return'}.</p>{detail.assignments.map(a=><p key={a.id}><Link to={`/events/events/${a.event_id}`}>{a.event_name}</Link> · {a.event_date?.slice(0,10)} · {a.released_at?'Released':a.lifecycle_status||a.acknowledgment_status||'Assigned'}</p>)}{!detail.assignments.length&&<p>No event assignments.</p>}<DataTable rows={detail.history.map((h,i)=>({...h,id:i}))} columns={['actor_name','action','created_at']} empty="No changes recorded."/><Link to="/events/calendar">Check availability in Calendar</Link></section>}
 {editing&&<div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="roster-title"><form className="modal" onSubmit={save}><h2 id="roster-title">{editing==='new'?'Create':'Edit'} {title.toLowerCase()}</h2>{error&&<div role="alert" className="toast error">{error}</div>}<div className="form-grid"><label>Name<input required value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></label>{(staff?[['email','Email','email'],['phone','Phone','tel'],['role','Role','text']]:[['category','Category','text'],['asset_uid','Asset code (generated if blank)','text'],['serial_number','Serial number','text']]).map(([key,label,type])=><label key={key}>{label}<input type={type} required={['category','role'].includes(key)} value={form[key]||''} onChange={e=>setForm(f=>({...f,[key]:e.target.value}))}/></label>)}{staff?<><label>Active<input type="checkbox" checked={form.active} onChange={e=>setForm(f=>({...f,active:e.target.checked}))}/></label><label>Linked user<RelationshipSelect resource="users" value={form.user_id} placeholder="User" onChange={value=>setForm(f=>({...f,user_id:value}))}/></label><label className="wide">Unavailable dates (YYYY-MM-DD, one per line)<textarea value={form.unavailable} onChange={e=>setForm(f=>({...f,unavailable:e.target.value}))}/></label><label className="wide">Notes<textarea value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></label></>:<label>Status<select value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value}))}>{['AVAILABLE','RESERVED','IN_USE','MAINTENANCE','RETIRED'].map(status=><option key={status}>{status}</option>)}</select></label>}</div><div className="modal-actions"><button type="button" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button><button className="primary-action" disabled={busy}>{busy?'Saving…':'Save'}</button></div></form></div>}
 </main>;
}
