import {useEffect,useRef,useState} from 'react';
import {Link,useLocation,useNavigate,useParams} from 'react-router-dom';
import {formatDateOnly,formatMoney} from '../utils/display.js';
import '../styles/client-workspace.css';
const host=window.location.hostname;
const API=host==='stagingadmin.thelolabooth.com'?'https://stagingapi.thelolabooth.com/api':host==='admin.thelolabooth.com'?'https://api.thelolabooth.com/api':import.meta.env.VITE_API_URL||'/api';
export default function SecureClientWorkspace(){
 const {eventId}=useParams(),location=useLocation(),navigate=useNavigate();
 const accessToken=useRef(location.pathname==='/client/access'?location.hash.slice(1):'');
 const [session,setSession]=useState(null),[workspace,setWorkspace]=useState(null),[email,setEmail]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[payment,setPayment]=useState(null),[amountChoice,setAmountChoice]=useState('FULL'),[customAmount,setCustomAmount]=useState('');
 async function request(path,options={}){
  const response=await fetch(API+'/public/client'+path,{credentials:'include',...options,headers:{'Content-Type':'application/json',...(session?{'X-Client-CSRF':session.csrfToken}:{}),...options.headers}});
  if(response.status===204)return null;const data=await response.json();if(!response.ok)throw new Error(data.error?.message||'Unable to open your workspace.');return data;
 }
 useEffect(()=>{if(location.hash&&location.pathname==='/client/access')window.history.replaceState(null,'','/client/access');},[]);
 useEffect(()=>{let active=true;setError('');setWorkspace(null);
  if(accessToken.current)return()=>{active=false;};
  request('/session').then(async data=>{
   if(!active)return;setSession(data);
   if(!eventId&&data.events.length){navigate('/client/events/'+data.events[0].id,{replace:true});return;}
   if(eventId){const view=await request('/events/'+eventId);if(active){setWorkspace(view);const outcome=new URLSearchParams(location.search).get('payment');if(outcome)setNotice(outcome==='success'?'Checkout returned. Your invoice and receipt update after the provider payment is verified.':'Checkout was cancelled. No payment is confirmed by this return page.');}}
  }).catch(e=>{if(active){setSession(null);if(eventId)setError(e.message);}});
  return()=>{active=false;};
 },[eventId,location.pathname]);
 async function run(action){if(busy)return;setBusy(true);setError('');setNotice('');try{await action();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function open(){await request('/access',{method:'POST',body:JSON.stringify({token:accessToken.current})});accessToken.current='';navigate('/client',{replace:true});}
 async function signIn(e){e.preventDefault();await run(async()=>{const result=await request('/sign-in',{method:'POST',body:JSON.stringify({email})});setNotice(result.message);});}
 async function download(path){await run(async()=>{const response=await fetch(API+'/public/client/events/'+eventId+path,{credentials:'include'});if(!response.ok){const result=await response.json();throw new Error(result.error?.message||'Document unavailable.');}const url=URL.createObjectURL(await response.blob());const a=window.document.createElement('a');a.href=url;a.download='LOLA-document.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
 async function paymentOptions(invoice){await run(async()=>{const options=await request('/events/'+eventId+'/invoices/'+invoice.id+'/payment-options');setPayment({invoice,options,key:crypto.randomUUID()});setAmountChoice('FULL');setCustomAmount('');});}
 async function pay(provider){await run(async()=>{const result=await request('/events/'+eventId+'/invoices/'+payment.invoice.id+'/payment-session',{method:'POST',body:JSON.stringify({provider,amountChoice,...(amountChoice==='CUSTOM'?{customAmount:Number(customAmount)}:{}),idempotencyKey:payment.key+':'+amountChoice+':'+customAmount})});const url=new URL(result.checkoutUrl);if(url.protocol!=='https:'||!(url.hostname==='checkout.stripe.com'||url.hostname==='paypal.com'||url.hostname.endsWith('.paypal.com')))throw new Error('Checkout address unavailable. Contact LOLA.');window.location.assign(url.href);});}
 return <div className="secure-workspace"><aside className="workspace-sidebar"><img src="/brand/LOLA_Primary_Dark_Transparent.png" alt="The LOLA Booth"/><p className="workspace-motto">Good people.<br/>Better photos.</p><nav aria-label="Client workspace">{workspace?<><a href="#workspace-home">Home</a><a href="#event-details">Event Details</a><a href="#planning">Planning & Creative</a><a href="#agreement">Agreement</a><a href="#payments">Invoices & Payments</a></>:<Link to="/client">Sign in</Link>}</nav><div className="workspace-help"><strong>Need help?</strong><a href="tel:7732402744">773-240-2744</a><a href="mailto:info@thelolabooth.com">info@thelolabooth.com</a></div></aside>
 <main id="workspace-home"><header><p className="eyebrow">The Client Workspace</p>{session&&<><button disabled={busy} onClick={()=>run(async()=>{const result=await request('/sign-in',{method:'POST',body:JSON.stringify({email:session.email})});setNotice(result.message);})}>Request fresh sign-in link</button><button disabled={busy} onClick={()=>run(async()=>{await request('/logout',{method:'POST'});setSession(null);setWorkspace(null);navigate('/client');})}>Sign out</button></>}</header>
 {error&&<p role="alert" className="workspace-error">{error}</p>}{notice&&<p role="status" className="workspace-notice">{notice}</p>}{payment&&<section className="workspace-card" aria-label="Invoice payment"><h2>Pay {payment.invoice.number}</h2><p>Outstanding balance {formatMoney(payment.options.fullAmount)}</p><label>Payment amount<select disabled={busy} value={amountChoice} onChange={e=>setAmountChoice(e.target.value)}><option value="FULL">Full remaining balance</option>{payment.options.depositAvailable&&<option value="DEPOSIT">Booking retainer fee remainder</option>}{payment.options.allowCustomAmount&&<option value="CUSTOM">Another amount</option>}</select></label>{amountChoice==='CUSTOM'&&<label>Amount <input type="number" min={payment.options.minimumAmount} max={payment.options.fullAmount} step="0.01" value={customAmount} onChange={e=>setCustomAmount(e.target.value)}/></label>}{payment.options.providers.map(provider=><button key={provider.provider} disabled={busy||(amountChoice==='CUSTOM'&&(!(Number(customAmount)>=payment.options.minimumAmount)||Number(customAmount)>payment.options.fullAmount))} onClick={()=>pay(provider.provider)}>Continue to {provider.label}</button>)}{!payment.options.providers.length&&<p>Online checkout is unavailable. Contact LOLA for payment options.</p>}<p>{payment.options.offlinePaymentInstructions}</p><button disabled={busy} onClick={()=>setPayment(null)}>Close payment options</button></section>}
 {accessToken.current?<section className="workspace-card workspace-login"><h1>Your secure workspace</h1><p>This sign-in link works once and expires after 15 minutes.</p><button className="workspace-gold" disabled={busy} onClick={()=>run(open)}>Open The Client Workspace →</button><Link to="/client" onClick={()=>{accessToken.current='';}}>Request a new link</Link></section>:!session?<section className="workspace-card workspace-login"><h1>Welcome back</h1><p>Enter your booking email to request a secure sign-in link.</p><form onSubmit={signIn}><label>Email address <span aria-label="required">*</span><input required type="email" autoComplete="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="workspace-gold" disabled={busy}>Send sign-in link</button></form></section>:!workspace?<p role="status">{session.events.length?'Opening your event…':'There are no available events in this workspace. Contact LOLA for help.'}</p>:<>
 <div className="workspace-event-heading"><div><h1>{workspace.event.name}</h1><p>{workspace.client} · {formatDateOnly(workspace.event.date)} · {workspace.event.venue||'Venue to be confirmed'}</p></div>{session.events.length>1&&<label>Your events<select value={eventId} onChange={e=>navigate('/client/events/'+e.target.value)}>{session.events.map(event=><option key={event.id} value={event.id}>{event.name} · {formatDateOnly(event.date)}</option>)}</select></label>}</div>
 <section className="workspace-card workspace-banner"><div><h2>Let’s bring your event to life.</h2><p>Review your booking, agreement and payments. We’re here if you need anything.</p><span className="workspace-status">{workspace.event.status.replaceAll('_',' ')}</span></div><img src="/brand/LOLA_Primary_Dark_Transparent.png" alt=""/></section>
 <div className="workspace-card-grid"><section id="event-details" className="workspace-card"><h2>Event Details</h2><p>Review your date, location and booking.</p><dl><dt>Date</dt><dd>{formatDateOnly(workspace.event.date)}</dd><dt>Location</dt><dd>{workspace.event.venue||'To be confirmed'}</dd><dt>Time</dt><dd>{workspace.event.start} – {workspace.event.end}</dd></dl></section>
 <section id="planning" className="workspace-card"><h2>Planning & Creative</h2><p>Choose your style, backdrop and review your designs.</p>{['CONFIRMED','PREPARING','READY','IN_PROGRESS'].includes(workspace.event.status)?<><Link to={'/client/events/'+eventId+'/planning'}>Continue Planning →</Link>{workspace.creative.map(proof=><p key={proof.id}><Link to={'/client/events/'+eventId+'/creative/'+proof.id}>{proof.type} · Version {proof.version} · {proof.status.replaceAll('_',' ')}</Link></p>)}</>:<p>Planning opens after your booking is confirmed.</p>}</section>
 <section className="workspace-card"><h2>Your Proposal</h2><p>{workspace.proposal.number} · {workspace.proposal.status.replaceAll('_',' ')}</p><p>Total <strong>{formatMoney(workspace.proposal.total)}</strong></p></section>
 <section id="agreement" className="workspace-card"><h2>Agreement</h2>{workspace.agreements.map(row=><article key={row.id}><p>{row.title}</p><p className="workspace-status">Signed by {row.signerName}</p><button disabled={busy} onClick={()=>download('/contracts/'+row.id+'/pdf')}>Download signed agreement</button></article>)}</section>
 <section id="payments" className="workspace-card"><h2>Invoices & Payments</h2>{workspace.invoices.map(row=><article key={row.id}><p>{row.number} · {row.status.replaceAll('_',' ')}</p><dl><dt>Total</dt><dd>{formatMoney(row.total)}</dd><dt>Paid</dt><dd>{formatMoney(row.paid)}</dd><dt>Balance</dt><dd><strong>{formatMoney(row.balance)}</strong></dd>{row.dueDate&&<><dt>Due</dt><dd>{formatDateOnly(row.dueDate)}</dd></>}</dl><button disabled={busy} onClick={()=>download('/invoices/'+row.id+'/pdf')}>Download invoice</button>{row.balance>0&&<button disabled={busy} onClick={()=>paymentOptions(row)}>View payment options</button>}</article>)}</section>
 <section className="workspace-card"><h2>Payment Receipts</h2>{workspace.receipts.length?workspace.receipts.map(row=><article key={row.id}><p>{formatMoney(row.amount)} · {row.status.replaceAll('_',' ')}</p>{Number(row.refundedAmount)>0&&<p>Refunded {formatMoney(row.refundedAmount)}</p>}<button disabled={busy} onClick={()=>download('/invoices/'+row.invoiceId+'/receipts/'+row.id+'/pdf')}>Download receipt</button></article>):<p>Receipts appear when payment is verified.</p>}</section></div>
 <footer className="workspace-card workspace-footer"><p>Thank you for choosing The LOLA Booth.<br/><em>Good people. Better photos.</em></p><a href="https://thelolabooth.com/availability.html">Book Another Event →</a></footer></>}
 </main></div>;
}
