import {RecordMetrics} from "../components/workspace/RecordWorkspace.jsx";
import RecordTable from "../components/workspace/RecordTable.jsx";
import StatusBadge from "../components/StatusBadge.jsx";
import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api/client.js';
import {useAuth} from '../context/AuthContext.jsx';
import AsyncState from '../components/AsyncState.jsx';
import {useDialogFocus} from '../utils/use-dialog-focus.js';
const aliases={homepage:'content',events:'eventTypes',pageItems:'pageItems',mediaMappings:'media'};
const fields={
 pageItems:[['page_slug','Page'],['slot_key','Page slot'],['html','Visible copy','textarea'],['href','Link']],
 hero:[['alt_text','Image description'],['caption','Caption'],['image','Image','image'],['fallback_image','Approved fallback','image']],
 experiences:[['name','Name'],['website_name','Website name'],['slug','Slug'],['website_heading','Heading'],['website_kicker','Supporting line'],['website_label','Label'],['website_short_description','Homepage description','textarea'],['website_long_description','Full description','textarea'],['features','Features (one per line)','lines'],['image','Image','image']],
 packages:[['name','Name'],['website_key','Package identity'],['pricing_mode','Pricing mode','pricing'],['starting_price','Starting price','number'],['website_short_description','Description','textarea'],['website_home_description','Homepage description','textarea'],['website_custom_heading','Custom heading'],['website_features','Features (one per line)','lines'],['image','Image','image']],
 eventTypes:[['name','Name'],['slug','Slug'],['short_description','Description','textarea'],['home_description','Homepage description','textarea'],['image','Image','image']],
 gallery:[['title','Title'],['caption','Caption','textarea'],['alt_text','Image description'],['category','Category'],['image','Image','image'],['fallback_image','Approved fallback','image']],
 testimonials:[['client_display_name','Client display name'],['event_type','Event type'],['quote','Quote','textarea'],['rating','Rating','number'],['client_photo','Photo','image']],
 faqs:[['question','Question'],['answer','Answer','textarea'],['category','Category']],
 content:[['content_key','Page key'],['title','Page title'],['seo_title','SEO title'],['seo_description','SEO description','textarea']],
 settings:[['value','Value','setting']],
 media:[['title','Title'],['alt_text','Image description'],['url','Approved asset URL'],['filename','Filename']]
};
const titles={pageItems:'Page Items',hero:'Hero Slides',experiences:'Experiences',packages:'Packages',eventTypes:'Event Types',gallery:'Gallery',testimonials:'Testimonials',faqs:'FAQs',content:'Page SEO',settings:'SEO & Site Settings',media:'Media Library'};
export default function StagingCms({section}){
 const type=aliases[section]||section,{can}=useAuth();
 const [homeContent,setHomeContent]=useState({hero:[],events:[]}),[category,setCategory]=useState(""),[statusFilter,setStatusFilter]=useState(""),[rows,setRows]=useState(null),[media,setMedia]=useState([]),[editing,setEditing]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[busy,setBusy]=useState(false);
 useDialogFocus(Boolean(editing),()=>setEditing(null));
 async function load(){setError('');try{const [r,m]=await Promise.all([api.get('/website/staging/'+type),api.get('/website/staging/media')]);setRows(r.data);setMedia(m.data.filter(x=>x.status==='PUBLISHED'));}catch(e){setError(e.message);}}
 useEffect(()=>{setCategory('');setRows(null);setEditing(null);setSearch('');setStatusFilter("");load();},[type]);
 useEffect(()=>{let active=true;if(section==='homepage')Promise.all([api.get('/website/staging/hero'),api.get('/website/staging/eventTypes')]).then(([hero,events])=>{if(active)setHomeContent({hero:hero.data||[],events:events.data||[]});}).catch(e=>active&&setError(e.message));return()=>{active=false;};},[section]);
 function edit(row){setEditing(row?{...row,payload:{...row.payload}}:{entity_key:'',payload:{},status:'DRAFT',display_order:rows?.length+1||1,channel:'STAGING'});}
 async function save(e){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const body={...editing,channel:'STAGING'};if(editing.id)await api.patch(`/website/staging/${type}/${editing.id}`,body);else await api.post(`/website/staging/${type}`,body);setEditing(null);setNotice('Saved to STAGING. Public website unchanged.');await load();}catch(err){setError(err.message);}finally{setBusy(false);}}
 async function action(row,act){if(busy)return;setBusy(true);try{await api.post(`/website/staging/${type}/${row.id}/${act}`,{});setNotice(`${act==='unpublish'?'Unpublished':act==='publish'?'Published':'Archived'} in STAGING only.`);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function upload(file){if(!file||busy)return;setBusy(true);try{const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});await api.post('/website/staging/upload',{filename:file.name,mimeType:file.type,data});setNotice('Uploaded to staging media.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 function recordActions(row){return <>{can('write:website')&&<button className="lola-secondary-button" onClick={()=>edit(row)}>Edit</button>}{can('publish:website')&&<><button disabled={busy} onClick={()=>action(row,row.status==='PUBLISHED'?'unpublish':'publish')}>{row.status==='PUBLISHED'?'Unpublish':'Publish'}</button><button disabled={busy} onClick={()=>action(row,'archive')}>Archive</button></>}</>;}
 const visible=(rows||[]).filter(r=>!category||(r.payload.category||"General")===category).filter(r=>!statusFilter||r.status===statusFilter).filter(r=>JSON.stringify(r.payload).toLowerCase().includes(search.toLowerCase())||r.entity_key.includes(search));
 return <main className="page cms-workspace record-module"><div className="page-heading lola-page-heading"><div><p className="eyebrow">Website CMS · STAGING</p><h1>{section==="homepage"?"Homepage":titles[type]||type}</h1><p className="lede">Update staging website content visually while keeping public V1 unchanged.</p></div><div className="button-row"><a className="lola-secondary-button" href="https://staging.thelolabooth.com" target="_blank" rel="noreferrer">Open staging website ↗</a>{can('write:website')&&<button className="primary-action" onClick={()=>edit(null)}>Add record</button>}</div></div>
 {notice&&<p role="status">{notice}</p>}{error&&<p role="alert" className="form-error">{error}</p>}
 {section==='homepage'&&<><RecordMetrics module="Content" rows={[...homeContent.hero,...homeContent.events]}/><section className="website-home-overview"><article className="record-panel"><header><div><h2>Hero Section</h2><p className="record-muted">Manage your homepage hero slides.</p></div><Link className="primary-action" to="/website/hero-slides">Manage Slides</Link></header><div className="website-hero-layout"><div>{homeContent.hero[0]?<CmsRecordPreview type="hero" payload={homeContent.hero[0].payload}/>:<p className="record-muted">Add a hero slide to showcase your brand.</p>}</div><div>{homeContent.hero.map(row=><Link className="website-hero-item" key={row.id} to="/website/hero-slides"><strong>{row.payload.caption||row.payload.alt_text||row.entity_key}</strong><StatusBadge status={row.status}/></Link>)}</div></div></article><article className="record-panel"><header><h2>Event Type Highlights</h2><Link to="/website/events">Edit Highlights →</Link></header><div className="website-highlight-grid">{homeContent.events.map(row=><Link key={row.id} to="/website/events"><CmsRecordPreview type="eventTypes" payload={row.payload}/><strong>{row.payload.name||row.entity_key}</strong></Link>)}</div></article><h2 className="website-page-seo-heading">Page SEO</h2></section></>}
 {section!=="homepage"&&<RecordMetrics module="Content" rows={rows||[]}/>}<div className="lola-status-tabs">{["","PUBLISHED","DRAFT","ARCHIVED"].map(status=><button key={status||"all"} className={statusFilter===status?"active":""} onClick={()=>setStatusFilter(status)}>{status||"All records"}</button>)}</div><div className="toolbar"><label>Search {titles[type]||"content"}<input value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
 {type==='media'&&can('write:website')&&<label>Upload staging image<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>upload(e.target.files[0])}/></label>}
 <div className={type==='faqs'?'website-faq-layout':'website-content-layout'}>{type==='faqs'&&<nav className="website-faq-categories" aria-label="FAQ categories"><button className={!category?"active":""} onClick={()=>setCategory('')}>All Questions ({(rows||[]).length})</button>{[...new Set((rows||[]).map(r=>r.payload.category||'General'))].map(cat=><button key={cat} className={category===cat?"active":""} onClick={()=>setCategory(cat)}>{cat} ({(rows||[]).filter(r=>(r.payload.category||'General')===cat).length})</button>)}</nav>}
 <AsyncState loading={rows===null} error={error} onRetry={load} noun="staging content">
   {!visible.length ? <section className="empty-state"><h2>No {titles[type]?.toLowerCase() || "content"} yet</h2><p>{search ? "Try a different search." : "Add your first record to begin shaping this section."}</p></section>  : type==='settings'?<section className="website-settings-grid">{visible.map(row=><article className="record-panel" key={row.id}><label>{recordTitle(row)}{typeof row.payload.value==='boolean'?<input type="checkbox" checked={row.payload.value} readOnly aria-label={recordTitle(row)}/>:<input readOnly value={String(row.payload.value??'')} aria-label={recordTitle(row)}/>}</label><div className="button-row">{recordActions(row)}</div></article>)}</section>: ["hero","gallery","media","experiences","packages","eventTypes"].includes(type) ? <section className={`cms-record-grid ${type==="experiences"?"website-experience-list":""}`}>
     {visible.map(row=><article className="cms-record-card" key={row.id} data-cms-record-id={row.id}>
       <CmsRecordPreview payload={row.payload} type={type}/>
       <div className="cms-record-body"><div className="table-heading"><h2>{recordTitle(row)}</h2><StatusBadge status={row.status}/></div>
         <p>{row.payload.caption || row.payload.website_short_description || row.payload.short_description || row.payload.quote || "Add a description in the editor."}</p>
         {type==='packages'&&<><strong className="website-package-price">{row.payload.pricing_mode==='CUSTOM'?"Let’s Talk":row.payload.starting_price!=null?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(row.payload.starting_price):'Price not set'}</strong><ul className="website-package-features">{(row.payload.website_features||[]).map((feature,index)=><li key={index}>{feature}</li>)}</ul></>}
         <div className="button-row">{recordActions(row)}</div>
       </div>
     </article>)}
   </section> : <RecordTable title={titles[type]||"Content"} rows={visible.map(row=>({...row,name:recordTitle(row),category:row.payload.category||row.payload.page_slug||"General"}))} columns={type==='testimonials'?["name","event_type","rating","quote","status"]:type==='settings'?["name","value","status"]:["name","category","status","display_order"]} renderCell={(row,column)=>column==='rating'?<span className="website-rating" aria-label={`${row.payload.rating||0} out of 5 stars`}>{'★'.repeat(Math.max(0,Math.min(5,Number(row.payload.rating)||0)))}</span>:column==='quote'?row.payload.quote:column==='event_type'?row.payload.event_type:column==='value'?String(row.payload.value??''):undefined} rowActions={recordActions}/>}

 </AsyncState></div>
 {editing&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Edit staging record"><h2>{editing.id?'Edit':'Create'} staging record</h2><p>Channel: <strong>STAGING</strong> · Current state: {editing.status}</p><form onSubmit={save}>{["hero","gallery","media","experiences","packages","eventTypes","testimonials"].includes(type)&&<CmsRecordPreview payload={editing.payload} type={type}/>}<label>Record key<input required value={editing.entity_key} onChange={e=>setEditing({...editing,entity_key:e.target.value})}/></label>
 {(fields[type]||[]).map(([key,label,kind])=>{const value=editing.payload[key];const change=v=>setEditing({...editing,payload:{...editing.payload,[key]:v}});return <label key={key}>{label}{kind==='image'?<select value={value||''} onChange={e=>change(e.target.value)}><option value="">Use approved fallback</option>{value&&!media.some(m=>m.payload.url===value)&&<option value={value}>Current image</option>}{media.map(m=><option key={m.id} value={m.payload.url}>{m.payload.title||m.entity_key}</option>)}</select>:kind==='pricing'?<select value={value||'STARTING'} onChange={e=>change(e.target.value)}><option>STARTING</option><option>CUSTOM</option></select>:kind==='setting'&&typeof value==='boolean'?<input type="checkbox" checked={value} onChange={e=>change(e.target.checked)}/>:kind==='textarea'||kind==='lines'?<textarea value={Array.isArray(value)?value.join('\n'):value||''} onChange={e=>change(kind==='lines'?e.target.value.split('\n'):e.target.value)}/>:<input type={kind==='number'?'number':'text'} value={value??''} onChange={e=>change(kind==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/>}</label>;})}
 <label>Sort order<input type="number" value={editing.display_order} onChange={e=>setEditing({...editing,display_order:Number(e.target.value)})}/></label><div className="form-actions"><button type="button" onClick={()=>setEditing(null)}>Cancel</button><button disabled={busy} type="submit">{busy?'Saving…':'Save staging record'}</button></div></form></section></div>}
 </main>;
}

function recordTitle(row){return row.payload.name || row.payload.website_name || row.payload.title || row.payload.question || row.payload.client_display_name || row.entity_key;}
function CmsRecordPreview({payload,type}){
 const image=payload.image || payload.client_photo || (type==="media"?payload.url:null) || payload.fallback_image;
 const [failed,setFailed]=useState(false);
 useEffect(()=>setFailed(false),[image]);
 return <figure className={`cms-record-preview cms-preview-${type}`}>
   {image&&!failed?<img loading="lazy" src={image} alt={payload.alt_text||payload.title||payload.name||"Content preview"} onError={()=>setFailed(true)}/>:<span>{failed?"Image unavailable":"Choose an image in the editor"}</span>}
   {type==="hero"&&payload.caption&&<figcaption>{payload.caption}</figcaption>}
 </figure>;
}
