import {useEffect,useState} from 'react';
import {useAppearance} from '../context/AppearanceContext.jsx';
import {DEFAULT_APPEARANCE,APPEARANCE_PALETTES,validAppearance} from '../../shared/admin-appearance.js';
import {Bars,Ring} from './workspace/InsightPanels.jsx';
const previewData=[{name:'Glam',value:42},{name:'360',value:28},{name:'Vogue',value:18},{name:'Audio',value:12}];
export default function AppearanceSettings(){
 const {saved,setPreview,save,error:loadError}=useAppearance();const [form,setForm]=useState({...saved}),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 useEffect(()=>{setForm({...saved});},[saved]);
 useEffect(()=>()=>setPreview(null),[setPreview]);
 function change(patch){const next={...form,...patch};setForm(next);if(validAppearance(next))setPreview(next);setNotice('');}
 async function persist(value=form){if(busy)return;setBusy(true);setError('');try{await save(value);setForm({...value});setNotice('Your appearance preferences are saved.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="settings-card appearance-settings"><h2>Appearance & Display</h2><p>Choose your personal admin view. The navigation stays black. Client pages and business branding keep their own appearance.</p>{(error||loadError)&&<p role="alert" className="toast error">{error||loadError}</p>}{notice&&<p role="status">{notice}</p>}<fieldset disabled={busy}><legend>View</legend><div className="button-row">{['DAY','NIGHT','AUTO'].map(mode=><label className="appearance-radio" key={mode}><input type="radio" name="appearance-mode" checked={form.mode===mode} onChange={()=>change({mode})}/>{mode==='AUTO'?'Auto · follow device':mode==='DAY'?'Day':'Night'}</label>)}</div></fieldset><fieldset disabled={busy}><legend>Admin background</legend><div className="button-row">{[['Ivory','#faf8f4'],['White','#ffffff'],['Sage','#e7eee8'],['Mist','#e8edf4'],['Blush','#f3e8e8']].map(([name,background])=><button type="button" key={name} aria-pressed={form.background===background} onClick={()=>change({background})}>{name}</button>)}</div><label>Custom background<input type="color" value={/^#[a-fA-F0-9]{6}$/.test(form.background)?form.background:DEFAULT_APPEARANCE.background} onChange={e=>change({background:e.target.value})}/></label><label>HEX color<input value={form.background} maxLength={7} pattern="#[a-fA-F0-9]{6}" onChange={e=>change({background:e.target.value})}/></label><p>Content cards retain readable surfaces. Night mode uses a dark workspace.</p></fieldset><fieldset disabled={busy}><legend>Chart & graph palette</legend>{Object.entries(APPEARANCE_PALETTES).map(([palette,colors])=><label className="appearance-radio" key={palette}><input type="radio" name="chart-palette" checked={form.palette===palette} onChange={()=>change({palette})}/>{palette==='ACCESSIBLE'?'Accessible':palette}<span className="appearance-swatches" aria-hidden="true">{colors.map(color=><i key={color} style={{background:color}}/>)}</span></label>)}<p>Labels and values stay visible alongside colors. Status colors retain their meanings.</p></fieldset><h3>Live preview · sample data</h3><div className="appearance-preview"><Bars data={previewData} vertical/><Ring data={previewData} label="Sample bookings"/></div><div className="button-row"><button className="primary-action" disabled={busy||!validAppearance(form)} onClick={()=>persist()}>{busy?'Saving…':'Save appearance'}</button><button disabled={busy} onClick={()=>{setForm({...saved});setPreview(null);setNotice('Preview reverted.');}}>Revert preview</button><button disabled={busy} onClick={()=>persist({...DEFAULT_APPEARANCE})}>Restore defaults</button></div></section>;
}
