import {useEffect,useState} from 'react';
import {api} from '../api/client.js';
import {useAuth} from '../context/AuthContext.jsx';
import {formatMoney} from '../utils/display.js';
export default function BackdropQuotePanel({eventId}){
 const {can}=useAuth();const [quote,setQuote]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[description,setDescription]=useState(''),[total,setTotal]=useState(''),[requiredPayment,setRequiredPayment]=useState(''),[invoiceId,setInvoiceId]=useState('');
 useEffect(()=>{let active=true;api.get('/events/'+eventId+'/backdrop-quote').then(value=>active&&setQuote(value)).catch(e=>active&&setError(e.message));return()=>{active=false;};},[eventId]);
 async function run(action){if(busy)return;setBusy(true);setError('');try{setQuote(await action());}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="panel"><h3>Custom / premium backdrop quote</h3>{error&&<p role="alert">{error}</p>}{quote?<><p>{quote.description}</p><p>{quote.status} · {formatMoney(quote.total)} · Required payment {formatMoney(quote.requiredPayment)}</p>{quote.status==='ACCEPTED'&&can('write:sales')&&<><label>Dedicated invoice ID<input value={invoiceId} onChange={e=>setInvoiceId(e.target.value)} disabled={busy||Boolean(quote.invoiceId)}/></label><button disabled={busy||Boolean(quote.invoiceId)||!invoiceId} onClick={()=>run(()=>api.post('/events/'+eventId+'/backdrop-quote/invoice',{invoiceId}))}>Link accepted quote invoice</button><p>Create an invoice for the exact quote total using Invoices, then link it here. Chargeable work requires the agreed net payment before confirmation.</p></>}{quote.invoiceId&&<p>Linked invoice: {quote.invoiceId}</p>}{!quote.invoiceId&&can('write:operations')&&<button disabled={busy} onClick={()=>{if(window.confirm('Withdraw this quote? Its issued terms and acceptance history will be retained.'))run(()=>api.post('/events/'+eventId+'/backdrop-quote/void',{quoteId:quote.id}));}}>Withdraw quote before invoice linkage</button>}</>:can('write:operations')&&<><label>Scope and deliverables<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={3000}/></label><label>Total price<input type="number" min="0.01" step="0.01" value={total} onChange={e=>setTotal(e.target.value)}/></label><label>Payment required before work<input type="number" min="0.01" step="0.01" value={requiredPayment} onChange={e=>setRequiredPayment(e.target.value)}/></label><button disabled={busy||description.trim().length<10||Number(requiredPayment)<=0||Number(total)<Number(requiredPayment)} onClick={()=>run(()=>api.post('/events/'+eventId+'/backdrop-quote',{description,total:Number(total),requiredPayment:Number(requiredPayment)}))}>Issue quote in client planning</button></>}</section>;
}
