import {api} from "../api/client.js";
import {useEffect,useState} from 'react';
import {AssetImage} from './ProposalVisualEditor.jsx';
const copyFields=[['intro','Introduction'],['event_intro','About the event'],['investment_title','Investment title'],['investment_intro','Investment introduction'],['experience_intro_style','Experience heading'],['why_us_title','Why LOLA title'],['why_us_intro','Why LOLA introduction'],['close_title','Closing title'],['close_body','Closing message'],['next_steps_intro','Next steps introduction'],['terms_intro','Terms & conditions']];
const optionalTitles=['Activation Goals','Creative Concept','Guest Journey','Brand Integration','Content Capture','Deliverables','Production Requirements','Staffing','Data Capture','Analytics / Reporting','Travel / Logistics','Timeline'];
export default function ProposalScenarioReview({scenario,overrides={},onChange,experiences=[],onExperiencesChange,assets:providedAssets=null}) {
  const [library,setLibrary]=useState([]);
  useEffect(()=>{if(providedAssets)return;let active=true;api.get('/proposal-assets').then(r=>{if(active)setLibrary(r.data||[]);}).catch(()=>{});return()=>{active=false;};},[providedAssets]);
  const assets=providedAssets||library;
  const [addTitle,setAddTitle]=useState(optionalTitles[0]);
  const copy={...scenario?.copy,...overrides.copy};
  const setCopy=(key,value)=>onChange({...overrides,copy:{...overrides.copy,[key]:value}});
  function updateExperience(item,patch){const id=item.experience_id||item.key;onChange({...overrides,experiences:{...overrides.experiences,[id]:{...overrides.experiences?.[id],...patch}}});}
  const slots=['cover','event',...experiences.map(item=>'experience:'+item.experience_id)];
  return <section className="wizard-section scenario-review"><h3>Proposal content</h3><p>Defaults are filled in for this event. Edits apply to this proposal only.</p>
    <div className="form-grid">{copyFields.map(([key,label])=><label key={key}>{label}<textarea rows={key.endsWith('title')?2:4} value={copy[key]??''} onChange={e=>setCopy(key,e.target.value)}/></label>)}
      <label>Next steps (one per line)<textarea rows={6} value={(copy.next_steps||[]).join('\n')} onChange={e=>setCopy('next_steps',e.target.value.split('\n'))}/></label>
      <label>Why LOLA highlights (title | description, one per line)<textarea rows={6} value={(copy.why_items||[]).map(item=>item.title+' | '+item.body).join('\n')} onChange={e=>setCopy('why_items',e.target.value.split('\n').filter(Boolean).map((line,index)=>{const [title,...body]=line.split('|');return{icon:copy.why_items?.[index]?.icon||'diamond',title:title.trim(),body:body.join('|').trim()};}))}/></label>
    </div>
    {experiences.map((item,index)=>{const composed=scenario?.experiences.find(row=>row.experience_id===item.experience_id)||item;const override=overrides.experiences?.[item.experience_id]||{};return <details key={item.experience_id} className="wizard-section"><summary>{item.name} — copy, inclusions & order</summary><div className="button-row"><button type="button" disabled={!index} onClick={()=>{const next=[...experiences];[next[index-1],next[index]]=[next[index],next[index-1]];onExperiencesChange(next);}}>Move up</button><button type="button" disabled={index===experiences.length-1} onClick={()=>{const next=[...experiences];[next[index],next[index+1]]=[next[index+1],next[index]];onExperiencesChange(next);}}>Move down</button></div><div className="form-grid"><label>Description<textarea value={override.description??composed.description??''} onChange={e=>updateExperience(item,{description:e.target.value})}/></label><label>Included features (one per line)<textarea rows={8} value={(override.features??composed.features??[]).join('\n')} onChange={e=>updateExperience(item,{features:e.target.value.split('\n').filter(Boolean)})}/></label></div></details>;})}
    <details className="wizard-section"><summary>Imagery — approved media</summary><p>Select an image from the approved library, or keep the scenario default.</p><div className="form-grid">{slots.map(slot=><label key={slot}>{slot.startsWith('experience:')?experiences.find(e=>slot==='experience:'+e.experience_id)?.name:slot==='cover'?'Cover':'Your event'}<select value={overrides.media?.[slot]?.[0]||''} onChange={e=>onChange({...overrides,media:{...overrides.media,[slot]:e.target.value?[e.target.value]:[]}})}><option value="">Scenario default</option>{assets.map(a=><option key={a.id} value={a.id}>{a.alt_text||a.filename||a.title||a.id}</option>)}</select>{overrides.media?.[slot]?.[0]&&<AssetImage id={overrides.media[slot][0]}/>}</label>)}</div></details>
    <details className="wizard-section"><summary>Add optional sections</summary><p>Add only confirmed services and deliverables. Catalog selections determine what is included.</p><div className="button-row"><select aria-label="Optional section" value={addTitle} onChange={e=>setAddTitle(e.target.value)}>{optionalTitles.map(t=><option key={t}>{t}</option>)}</select><button type="button" onClick={()=>onChange({...overrides,optional_sections:[...(overrides.optional_sections||[]),{title:addTitle,body:addTitle==='Activation Goals'?(scenario?.copy.goals||[]).join('\n'):''}]})}>Add section</button></div>{(overrides.optional_sections||[]).map((s,index)=><div className="form-grid" key={index}><label>Title<input value={s.title} onChange={e=>onChange({...overrides,optional_sections:overrides.optional_sections.map((v,i)=>i===index?{...v,title:e.target.value}:v)})}/></label><label>Content<textarea value={s.body} onChange={e=>onChange({...overrides,optional_sections:overrides.optional_sections.map((v,i)=>i===index?{...v,body:e.target.value}:v)})}/></label><button type="button" onClick={()=>onChange({...overrides,optional_sections:overrides.optional_sections.filter((_,i)=>i!==index)})}>Remove section</button></div>)}</details>
  </section>;
}
